### ISSUE TITLE
errors while installing  zmq.h: No such file or directory

### ISSUE THREAD

**Issue by thesios** [Snipa22/nodejs-pool#100]
make: Entering directory `/home/altcoinspo/nodejs-pool/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/home/altcoinspo/nodejs-pool/node_modules/zmq/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/altcoinspo/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.14.32-xxxx-grs-ipv6-64
gyp ERR! command "/home/altcoinspo/.nvm/versions/node/v6.9.2/bin/node" "/home/altcoinspo/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/altcoinspo/nodejs-pool/node_modules/zmq
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/altcoinspo/.nvm/versions/node/v6.9.2/bin/node" "/home/altcoinspo/.nvm/versions/node/v6.9.2/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

**Comment by thesios** [comment]
Found the issue , missing zmq devel libraries.

I am installing in CentOS 7 

Please close
