### ISSUE TITLE
pool module:  RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by emdaitaj** [Snipa22/nodejs-pool#108]
first of all thanks for develping and supporting ths script

i receive  "RangeError: Maximum call stack size exceeded " form pool module when it recieves the first share (note that it give work to the miner and accpts the share but immediately after it accept the first share

muh@static:~/nodejs-pool$ node init.js --module=pool --unsafe-perm
Master cluster setting up 8 workers...
Did not send e-mail successfully!  Response: undefined Response: undefined
Worker 3304 is online
Worker 3310 is online
Worker 3319 is online
Worker 3329 is online
Worker 3335 is online
Worker 3341 is online
Worker 3311 is online
Worker 3317 is online
(Master) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 1 - 3304) Started server on port: 3333
(Worker 1 - 3304) Started server on port: 5555
(Worker 1 - 3304) Started server on port: 7777
(Worker 1 - 3304) Started server on port: 9000
(Worker 6 - 3329) Started server on port: 3333
(Worker 6 - 3329) Started server on port: 5555
(Worker 6 - 3329) Started server on port: 7777
(Worker 6 - 3329) Started server on port: 9000
(Worker 5 - 3319) Started server on port: 3333
(Worker 5 - 3319) Started server on port: 5555
(Worker 5 - 3319) Started server on port: 7777
(Worker 5 - 3319) Started server on port: 9000
(Worker 2 - 3310) Started server on port: 3333
(Worker 2 - 3310) Started server on port: 5555
(Worker 2 - 3310) Started server on port: 7777
(Worker 2 - 3310) Started server on port: 9000
(Worker 4 - 3317) Started server on port: 3333
(Worker 4 - 3317) Started server on port: 5555
(Worker 4 - 3317) Started server on port: 7777
(Worker 4 - 3317) Started server on port: 9000
(Worker 7 - 3335) Started server on port: 3333
(Worker 7 - 3335) Started server on port: 5555
(Worker 7 - 3335) Started server on port: 7777
(Worker 7 - 3335) Started server on port: 9000
(Worker 8 - 3341) Started server on port: 3333
(Worker 8 - 3341) Started server on port: 5555
(Worker 8 - 3341) Started server on port: 7777
(Master) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 1 - 3304) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 2 - 3310) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 5 - 3319) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 7 - 3335) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 4 - 3317) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 6 - 3329) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 1 - 3304) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 8 - 3341) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 8 - 3341) Started server on port: 9000
(Worker 3 - 3311) New block to mine at height: 1388084.  Difficulty: 27343547048
(Worker 3 - 3311) Started server on port: 3333
(Worker 3 - 3311) Started server on port: 5555
(Worker 3 - 3311) Started server on port: 7777
(Worker 3 - 3311) Started server on port: 9000
(Master) Queue debug state: 0 items in the queue 0 items being processed
(Master) Queue debug state: 0 items in the queue 0 items being processed
(Master) Queue debug state: 0 items in the queue 0 items being processed
(Master) Queue debug state: 0 items in the queue 0 items being processed
(Master) Queue debug state: 0 items in the queue 0 items being processed
/home/muh/nodejs-pool/node_modules/extend/index.js:34
module.exports = function extend() {
                                ^

RangeError: Maximum call stack size exceeded
    at extend (/home/muh/nodejs-pool/node_modules/extend/index.js:34:33)
    at initParams (/home/muh/nodejs-pool/node_modules/request/index.js:36:5)
    at request (/home/muh/nodejs-pool/node_modules/request/index.js:48:16)
    at Function.post (/home/muh/nodejs-pool/node_modules/request/index.js:62:12)
    at /home/muh/nodejs-pool/lib/remote_comms.js:12:25
    at /home/muh/nodejs-pool/node_modules/async/dist/async.js:2937:44
    at apply (/home/muh/nodejs-pool/node_modules/async/dist/async.js:21:25)
    at /home/muh/nodejs-pool/node_modules/async/dist/async.js:56:12
    at Request._callback (/home/muh/nodejs-pool/lib/remote_comms.js:16:28)
    at self.callback (/home/muh/nodejs-pool/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.init (/home/muh/nodejs-pool/node_modules/request/request.js:234:17)
    at new Request (/home/muh/nodejs-pool/node_modules/request/request.js:130:8)
    at request (/home/muh/nodejs-pool/node_modules/request/index.js:54:10)
    at Function.post (/home/muh/nodejs-pool/node_modules/request/index.js:62:12)

i changed limits to but didn't make a difference (using ulinmit not for entire os)

muh@static:~/nodejs-pool$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 133045
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 133045
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

can it be from installation?

**Comment by emdaitaj** [comment]
for those wha get the same error:
i was getting this because i hadn't setted up "feeaddress" in mysql database (in "config" table)
