### ISSUE TITLE
edit ports 

### ISSUE THREAD

**Issue by coolsd** [Snipa22/nodejs-pool#109]
1|api      | 2017-08-31 20:46 +08:00: Unhandled rejection Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
1|api      |     at Query.Sequence._packetToError (/home/coolsd/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
1|api      |     at Query.ErrorPacket (/home/coolsd/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
1|api      |     at Protocol._parsePacket (/home/coolsd/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:280:23)
1|api      |     at Parser.write (/home/coolsd/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:74:12)
1|api      |     at Protocol.write (/home/coolsd/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
1|api      |     at Socket.<anonymous> (/home/coolsd/nodejs-pool/node_modules/mysql/lib/Connection.js:109:28)
1|api      |     at emitOne (events.js:96:13)
1|api      |     at Socket.emit (events.js:188:7)
1|api      |     at readableAddChunk (_stream_readable.js:176:18)
1|api      |     at Socket.Readable.push (_stream_readable.js:134:10)
1|api      |     at TCP.onread (net.js:548:20)
1|api      |     --------------------
1|api      |     at Pool.query (/home/coolsd/nodejs-pool/node_modules/mysql/lib/Pool.js:197:23)
1|api      |     at /home/coolsd/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
1|api      |     at Promise._execute (/home/coolsd/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
1|api      |     at Promise._resolveFromExecutor (/home/coolsd/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
1|api      |     at new Promise (/home/coolsd/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
1|api      |     at Pool.promiseCallback (/home/coolsd/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
1|api      |     at pool.query (/home/coolsd/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
1|api      |     at /home/coolsd/nodejs-pool/lib/api.js:826:18
1|api      |     at Layer.handle [as handle_request] (/home/coolsd/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
1|api      |     at next (/home/coolsd/nodejs-pool/node_modules/express/lib/router/route.js:131:13)
1|api      |     at Route.dispatch (/home/coolsd/nodejs-pool/node_modules/express/lib/router/route.js:112:3)
1|api      |     at Layer.handle [as handle_request] (/home/coolsd/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
1|api      |     at /home/coolsd/nodejs-pool/node_modules/express/lib/router/index.js:277:22
1|api      |     at Function.process_params (/home/coolsd/nodejs-pool/node_modules/express/lib/router/index.js:330:12)
1|api      |     at next (/home/coolsd/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
1|api      |     at /home/coolsd/nodejs-pool/lib/api.js:687:17

**Comment by norlover** [comment]
I have the same problem

**Comment by norlover** [comment]
2017-09-05 14:59 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (/home/pool/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/pool/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/pool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/pool/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/pool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/pool/nodejs-pool/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Pool.query (/home/pool/nodejs-pool/node_modules/mysql/lib/Pool.js:197:23)
    at /home/pool/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/home/pool/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/pool/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/pool/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
    at Pool.promiseCallback (/home/pool/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/home/pool/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
    at /home/pool/nodejs-pool/lib/api.js:826:18
    at Layer.handle [as handle_request] (/home/pool/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pool/nodejs-pool/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/pool/nodejs-pool/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pool/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at /home/pool/nodejs-pool/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/pool/nodejs-pool/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pool/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
    at /home/pool/nodejs-pool/lib/api.js:687:17
