### ISSUE TITLE
TypeError: Cannot create property 'fee' on boolean 'false'

### ISSUE THREAD

**Issue by propercoil** [Snipa22/nodejs-pool#129]
Getting this error after installation from the api:

```
TypeError: Cannot create property 'fee' on boolean 'false'
    at /home/pooldaemon/nodejs-pool/lib/api.js:385:28
```

`m2 show 1` results with the api status:
```
│ status            │ online                                     │
│ name              │ api                                        │
│ restarts          │ 3                                          │
│ uptime            │ 3m                                         │
│ script path       │ /home/pooldaemon/nodejs-pool/init.js       │
│ script args       │ --module=api                               │
│ error log path    │ /home/pooldaemon/.pm2/logs/api-error-1.log │
│ out log path      │ /home/pooldaemon/.pm2/logs/api-out-1.log   │
│ pid path          │ /home/pooldaemon/.pm2/pids/api-1.pid       │
│ interpreter       │ node                                       │
│ interpreter args  │ N/A                                        │
│ script id         │ 1                                          │
│ exec cwd          │ /home/pooldaemon/nodejs-pool               │
│ exec mode         │ fork_mode                                  │
│ node.js version   │ 6.9.2                                      │
│ watch & reload    │ ✘                                          │
│ unstable restarts │ 0                                          │
│ created at        │ 2017-10-05T20:03:14.533Z   
```

Full error:
```
 TypeError: Cannot create property 'fee' on boolean 'false'
    at /home/pooldaemon/nodejs-pool/lib/api.js:377:28
    at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at /home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:277:22
    at param (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:349:14)
    at param (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:410:3)
    at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/home/pooldaemon/nodejs-pool/node_modules/body-parser/lib/types/json.js:109:7)
    at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:312:13)
    at /home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
```

Api returns 500 on front end.

**Comment by propercoil** [comment]
One of the daemons wasn't up, my bad. You can close this.
