### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by uaktags** [Snipa22/nodejs-pool#136]
I'm getting the following which keeps causing the miner to disconnect:

```
7|pool     | 2017-10-24 01:33 +00:00: RangeError: Maximum call stack size exceeded
7|pool     |     at extend (/home/tgarrity/nodejs-pool/node_modules/extend/index.js:34:33)
7|pool     |     at initParams (/home/tgarrity/nodejs-pool/node_modules/request/index.js:35:5)
7|pool     |     at request (/home/tgarrity/nodejs-pool/node_modules/request/index.js:47:16)
7|pool     |     at Function.post (/home/tgarrity/nodejs-pool/node_modules/request/index.js:61:12)
7|pool     |     at /home/tgarrity/nodejs-pool/lib/remote_comms.js:12:25
7|pool     |     at /home/tgarrity/nodejs-pool/node_modules/async/dist/async.js:2937:44
7|pool     |     at apply (/home/tgarrity/nodejs-pool/node_modules/async/dist/async.js:21:25)
7|pool     |     at /home/tgarrity/nodejs-pool/node_modules/async/dist/async.js:56:12
7|pool     |     at Request._callback (/home/tgarrity/nodejs-pool/lib/remote_comms.js:16:28)
7|pool     |     at self.callback (/home/tgarrity/nodejs-pool/node_modules/request/request.js:186:22)
7|pool     |     at emitOne (events.js:96:13)
7|pool     |     at Request.emit (events.js:188:7)
7|pool     |     at Request.init (/home/tgarrity/nodejs-pool/node_modules/request/request.js:232:17)
7|pool     |     at new Request (/home/tgarrity/nodejs-pool/node_modules/request/request.js:128:8)
7|pool     |     at request (/home/tgarrity/nodejs-pool/node_modules/request/index.js:53:10)
7|pool     |     at Function.post (/home/tgarrity/nodejs-pool/node_modules/request/index.js:61:12)
7|pool     | 2017-10-24 01:33 +00:00: Master cluster setting up 2 workers...
7|pool     | 2017-10-24 01:33 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
7|pool     | 2017-10-24 01:33 +00:00: (Master) New block to mine at height: 882964.  Difficulty: 3326947571
7|pool     | 2017-10-24 01:33 +00:00: Worker 19122 is online
7|pool     | 2017-10-24 01:33 +00:00: Worker 19123 is online
7|pool     | 2017-10-24 01:33 +00:00: (Worker 1 - 19122) Started server on port: 3333
7|pool     | 2017-10-24 01:33 +00:00: (Worker 1 - 19122) Started server on port: 5555
7|pool     | 2017-10-24 01:33 +00:00: (Worker 1 - 19122) Started server on port: 7777
7|pool     | 2017-10-24 01:33 +00:00: (Worker 1 - 19122) Started server on port: 9000
7|pool     | 2017-10-24 01:33 +00:00: (Worker 2 - 19123) Started server on port: 3333
7|pool     | 2017-10-24 01:33 +00:00: (Worker 2 - 19123) Started server on port: 5555
7|pool     | 2017-10-24 01:33 +00:00: (Worker 2 - 19123) Started server on port: 7777
7|pool     | 2017-10-24 01:33 +00:00: (Worker 2 - 19123) Started server on port: 9000
7|pool     | 2017-10-24 01:33 +00:00: (Master) New block to mine at height: 882964.  Difficulty: 3326947571
7|pool     | 2017-10-24 01:33 +00:00: (Master) New block to mine at height: 882964.  Difficulty: 3326947571
```

**Comment by thisjrodriguez** [comment]
i too!

**Comment by Snipa22** [comment]
RemoteShare isns't setup properly: https://github.com/Snipa22/nodejs-pool/wiki/Configuration-Details

**Comment by thisjrodriguez** [comment]
Yes, @Snipa22 you are fucking best the fucking wolrd!

**Comment by uaktags** [comment]
Okay, so set it to just http://127.0.0.1:8000/leafApi . But it looks like 8000 seems to default listen on ipv6 rather than ipv4. Seems to be an issue with the fact that it just does app.listen and that doesn't specify an interface/ip to bind on.

**Comment by uaktags** [comment]
Doesn't appear to affect anything being ipv4/ipv6.
