### ISSUE TITLE
pool_db has no Active Readers

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#144]
When I run the command `mdb_stat -fear ~/pool_db/` that's the result:

```
Environment Info
  Map address: (nil)
  Map size: 25769803776
  Page size: 4096
  Max pages: 6291456
  Number of pages used: 486
  Last transaction ID: 400282
  Max readers: 512
  Number of readers used: 3
Reader Table Status
(no active readers)
Freelist Status
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 21
  Free pages: 307
Status of Main DB
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 3
Status of blocks
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 12
  Overflow pages: 0
  Entries: 407
Status of cache
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 8
  Overflow pages: 128
  Entries: 23
Status of shares
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 4
  Overflow pages: 0
  Entries: 331
```

I think this is related to the pool not making correct payments or not making payments at all. I'm using testnet for payments tests purposes and this is the current balance of my test wallets:

Pool wallet: 3574 XMR
Pool fee wallet: 0 XMR
Miner that found all the 407 blocks: 61 XMR

I formatted and reinstalled everything with the deploy.bash script many times, always getting the same results. Even tried with a different server.

I tried checking for errors with the `pm2 logs` command, but there doesn't seem to be anything wrong.

This is the current size of the pool_db LMDB:

```
:~/pool_db$ ls -lh
total 2.0M
-rw-r--r-- 1 pooldaemon pooldaemon 1.9M Oct 31 13:21 data.mdb
-rw-r--r-- 1 pooldaemon pooldaemon  33K Oct 31 13:21 lock.mdb
```

This is what I get from the blockManager module:

```
3|blockMan | 2017-10-31 13:21 +00:00: Performing PPS payout on block: 1029664 Block Value: 8.95719816759
3|blockMan | 2017-10-31 13:21 +00:00: PPS payout cycle complete on block: 1029664 Block Value: 8.95719816759 Block Payouts: 0 Payout Percentage: 0%
3|blockMan | 2017-10-31 13:21 +00:00: Scan complete, unlocking remainder of blockManager functionality.
```

How can I fix the no Active Readers issue?

Thanks

**Comment by Snipa22** [comment]
This isn't an issue with a lack of Active Readers.  We've tracked the bug back, I'll have a patch for it out in a day or so.

**Comment by vitorgatti** [comment]
Looking forward to this patch, thanks :)

**Comment by RomanSzabados** [comment]
I am also affected and looking forward for a fix!
Thank you for your great work!

**Comment by Snipa22** [comment]
Patches made, pull down, restart your longRunner, and this should stop trashing blocks/shares early.

**Comment by vitorgatti** [comment]
Hmm I updates with `git pull` and then restarted all the modules, but I'm still getting No Active Readers and the payments where not being done correctly (still random, pool wallet getting most of the profits or not paying at all).

I then tried a `npm install` and rebooted the server, will check if anything changes.

Also, the payments module is showing this on the logs:

```
5|payments |     at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at Request.emit (events.js:188:7)
5|payments |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at ClientRequest.emit (events.js:188:7)
5|payments |     at Socket.socketErrorListener (_http_client.js:310:9)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at Socket.emit (events.js:188:7)
5|payments |     at emitErrorNT (net.js:1278:8)
5|payments |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
5|payments |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by Snipa22** [comment]
Could I get the full response from that error?  There should not be any active readers anywhere in your system under normal usage.  All of the apps disconnect their readers due to the LMDB blocking systems.

**Comment by vitorgatti** [comment]
Oh ok, I thought the Active Readers was important because of your troubleshooting guide in the Readme file.

This is the payments module after a few hours of the pool running:

```
pooldaemon@vps5214:~$ pm2 logs payments
[TAILING] Tailing last 15 lines for [payments] process (change the value with --lines option)
/home/pooldaemon/.pm2/logs/payments-out-5.log last 15 lines:
5|payments | 2017-11-02 11:31 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 11:31 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 11:31 +00:00: Paying out: 2 people
5|payments | 2017-11-02 11:31 +00:00: Database Worker: LMDB Env Initialized.
5|payments | 2017-11-02 11:31 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 11:31 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 11:31 +00:00: Paying out: 2 people
5|payments | 2017-11-02 11:44 +00:00: Database Worker: LMDB Env Initialized.
5|payments | 2017-11-02 11:44 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 11:44 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 11:44 +00:00: Paying out: 2 people
5|payments | 2017-11-02 11:44 +00:00: Database Worker: LMDB Env Initialized.
5|payments | 2017-11-02 11:44 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 11:44 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 11:44 +00:00: Paying out: 2 people

/home/pooldaemon/.pm2/logs/payments-error-5.log last 15 lines:
5|payments |     at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at Request.emit (events.js:188:7)
5|payments |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at ClientRequest.emit (events.js:188:7)
5|payments |     at Socket.socketErrorListener (_http_client.js:310:9)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at Socket.emit (events.js:188:7)
5|payments |     at emitErrorNT (net.js:1278:8)
5|payments |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
5|payments |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
5|payments | 2017-11-02 11:44 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
5|payments | 2017-11-02 11:44 +00:00: Will not make more payments until the payment daemon is restarted!
5|payments | 2017-11-02 11:44 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
```

And this is after I restarted the payments module:

```
pooldaemon@vps5214:~$ pm2 logs payments
[TAILING] Tailing last 15 lines for [payments] process (change the value with --lines option)
/home/pooldaemon/.pm2/logs/payments-out-5.log last 15 lines:
5|payments | 2017-11-02 11:31 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 11:31 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 11:31 +00:00: Paying out: 2 people
5|payments | 2017-11-02 11:44 +00:00: Database Worker: LMDB Env Initialized.
5|payments | 2017-11-02 11:44 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 11:44 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 11:44 +00:00: Paying out: 2 people
5|payments | 2017-11-02 11:44 +00:00: Database Worker: LMDB Env Initialized.
5|payments | 2017-11-02 11:44 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 11:44 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 11:44 +00:00: Paying out: 2 people
5|payments | 2017-11-02 17:30 +00:00: Database Worker: LMDB Env Initialized.
5|payments | 2017-11-02 17:30 +00:00: Setting the payment timer to: 120 minutes with a: 25 minute delay if the wallet is out of money
5|payments | 2017-11-02 17:30 +00:00: Loaded all payees into the system for processing
5|payments | 2017-11-02 17:30 +00:00: Paying out: 3 people

/home/pooldaemon/.pm2/logs/payments-error-5.log last 15 lines:
5|payments |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at ClientRequest.emit (events.js:188:7)
5|payments |     at Socket.socketErrorListener (_http_client.js:310:9)
5|payments |     at emitOne (events.js:96:13)
5|payments |     at Socket.emit (events.js:188:7)
5|payments |     at emitErrorNT (net.js:1278:8)
5|payments |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
5|payments |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
5|payments | 2017-11-02 11:44 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
5|payments | 2017-11-02 11:44 +00:00: Will not make more payments until the payment daemon is restarted!
5|payments | 2017-11-02 11:44 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
5|payments | 2017-11-02 17:30 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
5|payments | 2017-11-02 17:30 +00:00: Will not make more payments until the payment daemon is restarted!
5|payments | 2017-11-02 17:30 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined

```

Screenshots of the pool:

Blocks found: 
![image](https://user-images.githubusercontent.com/5687102/32341061-931162f8-bfe3-11e7-8a8a-1952c897a387.png)

Payments: 
![image](https://user-images.githubusercontent.com/5687102/32341024-7c912194-bfe3-11e7-9226-be5a906e3643.png)

**Comment by vitorgatti** [comment]
More log info:

```
2017-11-02 11:44 +00:00: TypeError: Cannot read property 'fee' of undefined
    at /home/pooldaemon/nodejs-pool/lib/payment_systems/xmr.js:331:122
    at /home/pooldaemon/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2017-11-02 11:44 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
2017-11-02 11:44 +00:00: Will not make more payments until the payment daemon is restarted!
2017-11-02 11:44 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
2017-11-02 17:30 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
2017-11-02 17:30 +00:00: Will not make more payments until the payment daemon is restarted!
2017-11-02 17:30 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined

```

**Comment by Snipa22** [comment]
Could you run tail -n 60 /home/pooldaemon/.pm2/logs/payments-error-5.log and confirm that you're mining XMR for this?  The issue with: failed to get random outs tends to be due to the wallet-rpc not being launched with --trusted-daemon.

**Comment by vitorgatti** [comment]
```
pooldaemon@vps5214:~$ tail -n 60 /home/pooldaemon/.pm2/logs/payments-error-5.log
2017-11-02 01:40 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
Will not make more payments until the payment daemon is restarted!
2017-11-02 01:40 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
2017-11-02 11:31 +00:00: TypeError: Cannot read property 'fee' of undefined
    at /home/pooldaemon/nodejs-pool/lib/payment_systems/xmr.js:331:122
    at /home/pooldaemon/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2017-11-02 11:31 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
2017-11-02 11:31 +00:00: Will not make more payments until the payment daemon is restarted!
Did not send e-mail successfully!  Response: undefined Response: undefined
2017-11-02 11:44 +00:00: TypeError: Cannot read property 'fee' of undefined
    at /home/pooldaemon/nodejs-pool/lib/payment_systems/xmr.js:331:122
    at /home/pooldaemon/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2017-11-02 11:44 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
2017-11-02 11:44 +00:00: Will not make more payments until the payment daemon is restarted!
2017-11-02 11:44 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
2017-11-02 17:30 +00:00: Issue making payments{"code":-4,"message":"failed to get random outs"}
2017-11-02 17:30 +00:00: Will not make more payments until the payment daemon is restarted!
2017-11-02 17:30 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined

```

I'm mining XMR and running the RPC wallet with --trusted-daemon:

`pm2 start /usr/local/src/monero/build/release/bin/monero-wallet-rpc -- --rpc-bind-port 28082 --password-file ~/pool-testnet.pass --wallet-file ~/pool-testnet --disable-rpc-login --trusted-daemon --testnet
`

**Comment by mxjoe** [comment]
Hi,

I am currently the only miner on my pool ([SECUmine.net](https://secumine.net), and the first block was found 5 days ago. For that my pool got a reward of approx. 6 XMR. Strange thing is, I got paid only approx. 0.7 XMR from my pool to my private wallet, the rest ist still on the pool wallet. Shouldn't it be much more paid?
Is this maybe connected to the above problem?

**Comment by vitorgatti** [comment]
> Is this maybe connected to the above problem?

I think so. New installations of the pool are not working correctly for payments anymore, as far as I am concerned. I personally tried dozens of install with different setups, and never can get the payments right.

**Comment by Snipa22** [comment]
> Is this maybe connected to the above problem?

Check your blockmanager log.  You'll likely find that you didn't have enough shares to pay out a full block.  It should have a line that says the % paid, this is normal in a new PPLNS pool, until you hit 2n share depth.  It's also possible that if you're not running the latest code, it didn't clean up properly.

**Comment by vitorgatti** [comment]
> Also, testnet payouts have been wonky from people reporting them.

The only way I can be 99.9% sure that my pool will work is if I can get the payments to work well in testnet, because I can find a block every 5 minutes with 50H/s. 

Many people are reporting incorrect payments in mainnet. Maybe the new patch fixes the issue, but an average pool usually takes weeks/months to find a block, and if by then it doesn't pay its miners correctly, people will not mine in that pool anymore. Testnet should work so we can be sure the pool won't let miners unpayed.

**Comment by Snipa22** [comment]
A standard pool would not find a block every 5 minutes.  A standard pool would find a block at a reasonable hashrate, and therefore, would pay out a reasonable amount.  Assuming you find a block every 5 minutes, then you're paying out 120/5*6-7, which means a payout of 24*6, or about 120-ish XMR per payout cycle, on a network not designed to handle transactions like that.

**Comment by vitorgatti** [comment]
But big pools (like minexmr.com) find a block every 10 minutes... the issue here is that we can't be sure that the pool will pay the miners after weeks of work.

No way to get testnet working? :(

**Comment by Snipa22** [comment]
Yes, but they're not paying 120 XMR to a single address, they pay XMR in smaller amounts to multiple addresses.  I strongly suggest looking up how RingCT works, and how the number of outputs and sizes make it hard to handle transactions.  The most obvious example I can come up with is when trying to transact > 1k XMR on even public chain, it breaks.  I also noted above, change your payout timing, and it should be fine.  You need to not let balances build up so much.

**Comment by mxjoe** [comment]
Hi Snipa22,

I checked my blockManager log. It has many messages like that.

`4|blockMan | 2017-11-07 06:05 +00:00: PPS payout cycle complete on block: 1437443 Block Value: 6.121477204772 Block Payouts: 0 Payout Percentage: 0%
4|blockMan | 2017-11-07 06:05 +00:00: Scan complete, unlocking remainder of blockManager functionality.`

**Comment by Snipa22** [comment]
You're specifically looking for PPLNS payout cycle, not PPS payout cycle.

**Comment by mxjoe** [comment]
Payout increased the last to blocks but is far from what was mined by the miner (me).

`4|blockMan | 2017-11-08 10:16 +00:00: Performing PPLNS payout on block: 1438289 Block Value: 5.968485100142`

`4|blockMan | 2017-11-08 10:16 +00:00: PPLNS payout cycle complete on block: 1438289 Block Value: 5.968485100142 Block Payouts: 2.626493722336 Payout Percentage: 44.00603634368647%`
