### ISSUE TITLE
longRunner module "Cannot read property 'hash' of null"

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#145]
```
pooldaemon@vps5214:~$ pm2 logs longRunner
[TAILING] Tailing last 15 lines for [longRunner] process (change the value with --lines option)
/home/pooldaemon/.pm2/logs/longRunner-out-7.log last 15 lines:
7|longRunn | 2017-11-04 20:00 +00:00: Database Worker: LMDB Env Initialized.
7|longRunn | 2017-11-04 20:00 +00:00: Cleaning up the share DB

/home/pooldaemon/.pm2/logs/longRunner-error-7.log last 15 lines:
7|longRunn |     at nextTask (/home/pooldaemon/nodejs-pool/node_modules/async/dist/async.js:5070:14)
7|longRunn |     at Object.waterfall (/home/pooldaemon/nodejs-pool/node_modules/async/dist/async.js:5073:5)
7|longRunn |     at Database.cleanShareDB (/home/pooldaemon/nodejs-pool/lib/local_comms.js:582:15)
7|longRunn |     at Object.<anonymous> (/home/pooldaemon/nodejs-pool/lib/longRunner.js:4:17)
7|longRunn |     at Module._compile (module.js:570:32)
7|longRunn |     at Object.Module._extensions..js (module.js:579:10)
7|longRunn |     at Module.load (module.js:487:32)
7|longRunn |     at tryModuleLoad (module.js:446:12)
7|longRunn |     at Function.Module._load (module.js:438:3)
7|longRunn |     at Module.require (module.js:497:17)
7|longRunn |     at require (internal/module.js:20:19)
7|longRunn |     at /home/pooldaemon/nodejs-pool/init.js:96:17
7|longRunn |     at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
7|longRunn |     at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
7|longRunn |     at Promise._settlePromise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
```

Full log file:

```
2017-11-04 20:08 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'hash' of null
    at /home/pooldaemon/nodejs-pool/lib/local_comms.js:584:72
    at nextTask (/home/pooldaemon/nodejs-pool/node_modules/async/dist/async.js:5070:14)
    at Object.waterfall (/home/pooldaemon/nodejs-pool/node_modules/async/dist/async.js:5073:5)
    at Database.cleanShareDB (/home/pooldaemon/nodejs-pool/lib/local_comms.js:582:15)
    at Object.<anonymous> (/home/pooldaemon/nodejs-pool/lib/longRunner.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/pooldaemon/nodejs-pool/init.js:96:17
    at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
```

I have just formatted my server, installing the pool from scratch, not mining currently, running in testnet mode.

Can I ignore this or is it going to affect something?

Thank you

**Comment by Snipa22** [comment]
I assume you're mining Monero and your pool is configured for XMR?

**Comment by vitorgatti** [comment]
Yes, I'm using the default settings. The only thing that I changed was the daemon ports (because testnet) and testnet flag has been set to 1. The rest is the default (following the installation guide).

**Comment by Snipa22** [comment]
Sounds like the block template isn't loading properly. Could you curl http://127.0.0.1:<daemon_port>/getinfo and check to see what the state is listed there?

**Comment by vitorgatti** [comment]
```
pooldaemon@vps5214:~$ curl http://127.0.0.1:28081/getinfo
{
  "alt_blocks_count": 2,
  "block_size_limit": 600000,
  "cumulative_difficulty": 34764434822,
  "difficulty": 32434,
  "grey_peerlist_size": 593,
  "height": 1032760,
  "incoming_connections_count": 7,
  "outgoing_connections_count": 9,
  "start_time": 1509824157,
  "status": "OK",
  "target": 120,
  "target_height": 1032750,
  "testnet": true,
  "top_block_hash": "3707e010f54682218fb1def8a60a16279800aa5d29e72f0eb2f840cf11694982",
  "tx_count": 50986,
  "tx_pool_size": 0,
  "white_peerlist_size": 18
}
```

```
pooldaemon@vps5214:~$ curl http://127.0.0.1:28082/getinfo
pooldaemon@vps5214:~$ 
```

**Comment by vitorgatti** [comment]
Any news?

**Comment by Snipa22** [comment]
No idea offhand, that should be working fine.  All of the pools using this version at this point in time on mainnet are showing it working fine.

**Comment by ArqTras** [comment]
Confirm that issue exist. I have the same problem but coin aeon. Fresh installation on ubuntu 16.04

**Comment by ArqTras** [comment]
arek@mine:~/nodejs-pool$ node init.js --module=longRunner
Database Worker: LMDB Env Initialized.
Cleaning up the share DB
Unhandled rejection TypeError: Cannot read property 'hash' of null
    at /home/arek/nodejs-pool/lib/local_comms.js:580:72
    at nextTask (/home/arek/nodejs-pool/node_modules/async/dist/async.js:5070:14                                                                                        )
    at Object.waterfall (/home/arek/nodejs-pool/node_modules/async/dist/async.js                                                                                        :5073:5)
    at Database.cleanShareDB (/home/arek/nodejs-pool/lib/local_comms.js:578:15)
    at Object.<anonymous> (/home/arek/nodejs-pool/lib/longRunner.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/arek/nodejs-pool/init.js:96:17
    at tryCatcher (/home/arek/nodejs-pool/node_modules/bluebird/js/release/util.                                                                                        js:16:23)
    at Promise._settlePromiseFromHandler (/home/arek/nodejs-pool/node_modules/bl                                                                                        uebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/arek/nodejs-pool/node_modules/bluebird/js/r                                                                                        elease/promise.js:567:18)

**Comment by vitorgatti** [comment]
@Snipa22 please take a look at @MineMoneroPRO's commit, it solved my issue.
