### ISSUE TITLE
Pool crashes with "TypeError: Cannot read property 'blocktemplate_blob' of undefined"

### ISSUE THREAD

**Issue by propercoil** [Snipa22/nodejs-pool#148]
This error occurs in the pool module after receiving` (Worker 4 - 17155) Excessive packet size from ` errors:

```
2017-11-06 20:39 +00:00: TypeError: Cannot read property 'blocktemplate_blob' of undefined
    at /home/pooldaemon/nodejs-pool/lib/pool.js:161:48
    at /home/pooldaemon/nodejs-pool/lib/coins/xmr.js:75:20
    at /home/pooldaemon/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:762:12)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-11-06 20:39 +00:00: Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Worker.send (cluster.js:64:28)
    at /home/pooldaemon/nodejs-pool/lib/pool.js:127:16
    at Array.forEach (native)
    at sendToWorkers (/home/pooldaemon/nodejs-pool/lib/pool.js:126:16)
    at Worker.messageHandler (/home/pooldaemon/nodejs-pool/lib/pool.js:88:17)
    at emitTwo (events.js:111:20)
    at Worker.emit (events.js:191:7)
    at ChildProcess.Worker.process.on (cluster.js:53:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by javietanh** [comment]
Check the Monero Demon running.

**Comment by ArqTras** [comment]
Check pool address in sql it should be wallet address not ip address
