### ISSUE TITLE
worker Email problem

### ISSUE THREAD

**Issue by RlyehDoom** [Snipa22/nodejs-pool#163]
![2017-11-13_16-56-34](https://user-images.githubusercontent.com/1031037/32746228-b30e9810-c893-11e7-9cd7-44e4fd85ba73.png)

Hello @Snipa22 I found this error and seems to be related with Email sender

2017-11-13 19:34 +00:00: Unhandled rejection SyntaxError: [sprintf] unexpected placeholder
    at sprintf_parse (/home/rlyeh/nodejs-pool/node_modules/sprintf-js/src/sprintf.js:189:23)
    at sprintf (/home/rlyeh/nodejs-pool/node_modules/sprintf-js/src/sprintf.js:26:31)
    at /home/rlyeh/nodejs-pool/lib/worker.js:233:41
    at tryCatcher (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/rlyeh/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

Data used by the function "global.support.sendEmail" is set on mysql:
![2017-11-13_17-54-38](https://user-images.githubusercontent.com/1031037/32748696-cd631b52-c89b-11e7-93c0-233be7f05002.png)

**Comment by RlyehDoom** [comment]
Ooops! the problem was the syntax sprintf needed "%(worker)s" the "s" at the end is data convert type (string) 👍
