### ISSUE TITLE
Creating leaf node - instruction 

### ISSUE THREAD

**Issue by ArqTras** [Snipa22/nodejs-pool#174]
Is there an instruction how to create second node on next vps to connect to one pool. Except deploy script I can’t find info how to connect to existing pool

**Comment by mxjoe** [comment]
As far as I know there is no documentation for installing a leaf node, just the bash file.

**Comment by mxjoe** [comment]
I am currently having trouble setting a leaf node up. The leaf.bash installation worked but the steps after that (files to edit, daemons to start ...) are unknown to me and I am currently doing trial and error.

**Comment by ArqTras** [comment]
Any success ?

**Comment by mxjoe** [comment]
Not yet.

**Comment by bobbieltd** [comment]
I’m interested in this, too. Will leaf node use remotely the main server’s database ?

**Comment by jredwine2857** [comment]
Looks like it uses the local db for some things related to blocks etc, but payments etc are handled at whatever you pick as your main node.  At the moment I've had some issues getting the leaf node to communicate with the main node.  I can see the tcp connection from the leaf node but it doesn't appear to be doing much.

**Comment by ArqTras** [comment]
Put leafApi public domain address in mysql

**Comment by mxjoe** [comment]
@ArqTras Could you go a bit more in detail, please.

**Comment by bobbieltd** [comment]
@ArqTras We put shareHost at same leafApi. What about modules ? Which modules do we need to run at leaf ? Do we still need same pool_db at leaf ? Thanks.

**Comment by ArqTras** [comment]
remoteShare and pool should be on node started.
They need to connect to main database.
You need to add id and ip and domain name in pools (mysql) also set it as active
You need to add ports to mine to on id 1 (example) 
You need to configure node as id 1 with public ip in config.json and mysql connection to main database.
Remember to secure Mysql connection.
Remember that daemon should be on rpc mode in node.

**Comment by jredwine2857** [comment]
So this part is a little wild west since there isn't much documentation on it.  My assumption was that all leafnodes would simply communicate with the DB via the leafAPI.  According to ArqTras it appears you actually have to open MySQL up to the leafnode as well.  Seems redundant, but I'll try it out and see how it goes.  

So far, just with pointing the leaf node's remoteshare setting to the main node, I can see communication via tcp and the pool starts ok, but if I mine to the leafnode, I do not see that reflected on the main node.  I.e. Things like connected miners, pool hashrate, all stay at 0.

Snipa, if you're looking at this, can you clear this up once and for all?  Does all comm from leafnode to main node happen over the leafAPI, or do we need to expose MySQL to the leafnode as well?

**Comment by ArqTras** [comment]
If you look at : 
https://github.com/Snipa22/nodejs-pool/blob/master/deployment/leaf.bash
Line 15 there is installation of nodejs so it should be configured like : 
https://github.com/Snipa22/nodejs-pool/blob/master/config_example.json

"mysql": {
    "connectionLimit": 20,
    "host": "127.0.0.1",
    "database": "pool",
    "user": "pool",
    "password": "98erhfiuehw987fh23d"
}
That is how node communicate to pool (ip and credentials) I think but if you have proof of work using only leafApi please share Your solution

**Comment by jredwine2857** [comment]
yeah, i dont have this working at all.  I've tried using just the leaf.bash to install a leafnode, and I assume (without documentation, i'm guessing here) that you would only need the Pool module started.  I set it up so that the config.json file points to the external IP of the MySQL server (and yes it's locked down to just the source IP of the leaf node).   Still no go.  The only logging I see is in the pool module error log and it's talking about an error parsing the JSON info which I assume is being sent from the leafAPI.  See below.

I have also tried installing using the full install script, though I haven't tried with opening up MySQL and pointing it at the MySQL server.  Going to try that next, but so far it's snake eyes on getting it to work using the lightweight leaf.bash script.

Could definitely use a little documentation on this process.  If I end up figuring it out, I'll post it here.





2018-01-06 07:50 +00:00: SyntaxError: Unexpected string in JSON at position 132
    at Object.parse (native)
    at Object.<anonymous> (/home/ubuntu/nodejs-pool/init.js:11:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/lib/ProcessContainerFork.js:78:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

**Comment by ArqTras** [comment]
On main server :
In MySQL leafApi as public and also public available 
Add 1 and ip and domain name in pools
Add ports with id 1 and ip in port configuration
Open acces to pool user and secure connection between node and main (you should be able connect as pooluser with default credentials)
On node aeond with the same config as master 
Start pool and remiteShare module

**Comment by ArqTras** [comment]
https://github.com/ArqTras/nodejs-pool/wiki/Leaf-Node-Wiki

**Comment by bobbieltd** [comment]
Great guide. Thank you ArqTras, I’ll practice to install a leaf next week when I have time.

**Comment by ArqTras** [comment]
Remember to add firewall rules on your server and allow connect to mysql - this is my solution I use but if anyone have better with is working please share info

**Comment by jredwine2857** [comment]
Thanks arqtras!  Huge contribution!

**Comment by ArqTras** [comment]
Working for me setup few hours ago ;)

**Comment by mxjoe** [comment]
mine isn't working yet, I managed to connect to the master node via MySQL and added the entries for leaf node in pool.ports and pool.pools. But I still get following error:

4|pool     | 2018-01-10 20:43 +00:00: TypeError: Cannot read property 'height' of undefined
4|pool     |     at Timeout._onTimeout (/home/user/nodejs-pool/lib/pool.js:833:115)
4|pool     |     at ontimeout (timers.js:475:11)
4|pool     |     at tryOnTimeout (timers.js:310:5)
4|pool     |     at Timer.listOnTimeout (timers.js:270:5)

Any ideas?

**Comment by mxjoe** [comment]
Thank you so much for the guide, @ArqTras ! Now it worked, the only thing I did was wait two days (no kidding) and upgrade my mailgun account. Strange, very strange...

**Comment by ArqTras** [comment]
@mxjoe you need to add credit card and put limit to 10000 emails :D

**Comment by mxjoe** [comment]
That's what I did and that seemed to fix my not working leaf node. :)

**Comment by ArqTras** [comment]
Also if you see I removed 9000 port with ssl because this making error for pool

**Comment by bobbieltd** [comment]
I don’t understand why 9000 doesn’t work when some others got in work (SSL, not TCP), and why it makes error with 9000 ?

**Comment by ArqTras** [comment]
multi node configuration (separate api, separate leaf node and other stuff) ;) read carefully whole readme and wiki from Snippa

**Comment by 78bash** [comment]
Thanks @ArqTras for the great wiki, but why my leaf doesn't listen on any pool port?

**Comment by jredwine2857** [comment]
Sounds like your leaf node isn't pulling the port config from the mysql db.  Check to make sure of the following:

-you have mysql access allowed inbound to your MySQL db

-that you are using a MySQL account with proper access (test doing a remote connection to your MySQL db using that account and verify you can 'select * from pool.config')

-that your global.json has the proper IP for your mysql server

Good luck!

**Comment by 78bash** [comment]
I did those, all is setup fine :/

**Comment by jredwine2857** [comment]
Could try a sudo reboot just to see if it will trigger something. I had to do some rebooting to kick it in the but after making a lot of changes. 

Also, check the nodejspool folder and see if any error logs are showing up.  Then check the pm2 logs by doing a 'pm2 show pool' and open the 2 logs it shows in nano.  See if that sheds any light.

**Comment by ArqTras** [comment]
Mysql on master must allow remote connection. You need to grant access from wan and secure that connection ex using iptables to allow connect from node public ip. It is really danger to open mysql to world so remember that connection between servers must be as much secure as you can. And you need to know that in myslq is default user with default password if you dont change it and open your mysql server everyone can connect using default credentials

**Comment by ArqTras** [comment]
On node:
"mysql": {
"connectionLimit": 20,
"host": "master pool ip",
"database": "pool",
"user": "pool",
"password": "98erhfiuehw987fh23d"
}
read carefully leaf wiki

**Comment by 78bash** [comment]
I found the issue, i cloned uaktags's repo by mistake instead of Snipa's for my xmr pool. Thanks for the help guys.

**Comment by ArqTras** [comment]
Yes that's really old wiki. Anyone can use actual version of Snipa's code and correct that values in leaf.bash and deploy.bash or simply use master branch to run.
