### ISSUE TITLE
Help! Cannot read property 'block_header' of undefined

### ISSUE THREAD

**Issue by RlyehDoom** [Snipa22/nodejs-pool#188]
Sometimes i got this error on my worker_error log. (I can trigger calls to the RPC without problems for ex.: curl -X POST http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getlastblockheader"}' -H 'Content-Type: application/json'

Bu anyways sometimes the worker logs this:
`2017-11-28 05:20 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18081}
2017-11-28 05:20 +00:00: TypeError: Cannot read property 'block_header' of undefined
    at /home/rlyeh/nodejs-pool/lib/worker.js:448:31
    at /home/rlyeh/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/rlyeh/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/rlyeh/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/rlyeh/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/rlyeh/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

**Comment by ArqTras** [comment]
Its because aeond storing file on disk - normal

**Comment by RlyehDoom** [comment]
Thanks for answer! @ArqTras So you are saying this is a normal behaviour? now I can sleep in peace...

**Comment by Snipa22** [comment]
Yes, this should be trapped somewhere in the logs, so if it's crashing your code, you may want to make sure you're on the latest updates, but yes, this is due to aeond being silly.

**Comment by RlyehDoom** [comment]
Thanks @Snipa22 and yes I'm using the lastest code.

**Comment by Bathmat** [comment]
Possible fix here: https://github.com/Snipa22/nodejs-pool/issues/412
