### ISSUE TITLE
Block found but no payout to miners

### ISSUE THREAD

**Issue by RlyehDoom** [Snipa22/nodejs-pool#190]
This is the only log I can found about the payment:

2017-12-06 02:59 +00:00: PPLNS payout cycle complete on block: 1054972 Block Value: 6.135092982895 Block Payouts: 5.42768982544 Payout Percentage: 75.30896076143046%

Miners can see they DUE balance but not payout(tx) is made.

**Comment by RlyehDoom** [comment]
The Payments api only logged this:
`Loaded all payees into the system for processing.`

**Comment by vitorgatti** [comment]
testnet?

did you remove --restricted-rpc from monerod?

**Comment by RlyehDoom** [comment]
Yes I'm running testnet without '--restricted-rpc'

**Comment by vitorgatti** [comment]
check balance of your wallets in mysql:

select * from pool.balance;

there are 2 wallets starting with 4 that are dev donation
if it reaches the threshold of them, monero-wallet-rpc will error out trying to send a payment to an invalid address (because it's not testnet wallet), so you'll have to manually put 0 on their balance in mysql

**Comment by RlyehDoom** [comment]
Before running testnet I got the precaution to set them 0% fee so they have balance Amount=0 right now. 
Only the Main address and Fee address got balance.

**Comment by RlyehDoom** [comment]
I deleted all the rows with balance = 0 so only the Main address and Fee address where active and I got a Payout done! I guess you where right even if the Devdonation is equal to 0 is trying to do something with them...

**Comment by vitorgatti** [comment]
you should not set devdonation to 0 btw, but that's none of my business :P

**Comment by RlyehDoom** [comment]
Was only for testnet I knew they have other type of address, should be a flag on the payment api asking if is running on testnet (the config parameter is already there)

**Comment by RlyehDoom** [comment]
Now im testing with 2 miners but only one of them is getting pay. And the payment log say:

`2017-12-07 01:01 +00:00: TypeError: Cannot read property 'fee' of undefined
    at /home/**/nodejs-pool/lib/payment_systems/xmr.js:331:122
    at /home/**/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/**/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/**/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/**/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/**/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)`
