### ISSUE TITLE
api/network/stats returns 'false'

### ISSUE THREAD

**Issue by rest2t** [Snipa22/nodejs-pool#202]
api/network/stats returns 'false', on electroneum daemon. Please help me :/

**Comment by rest2t** [comment]
I only run deploy.sh. I have changed daememon etc. for etn.

**Comment by ArqTras** [comment]
write to me support@ar-net.info mayby I can help

**Comment by JPaulMora** [comment]
I got this traceback:

````
TypeError: Cannot create property 'fee' on boolean 'false'
   at /home/pooldaemon/nodejs-pool/lib/api.js:253:28
   at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
   at /home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:277:22
   at param (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:349:14)
   at param (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:410:3)
   at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
   at jsonParser (/home/pooldaemon/nodejs-pool/node_modules/body-parser/lib/types/json.js:109:7)
   at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:312:13)
   at /home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:330:12)
   at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
````

**Comment by ArqTras** [comment]
fee wallet address (wallet not ip) in sql

**Comment by JPaulMora** [comment]
It seems the database class/function at `lib/local_comms` isn't being initialized correctly. When api calls database.getCache it returns `false`. Since the api creates multiple threads/ calls the code multiple times, it sometimes works and gives a correct response and the other times creates the error above.
