### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by CollusionPool** [Snipa22/nodejs-pool#209]
`2017-12-15 09:54 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: ER_CON_COUNT_ERROR: Too many connections
    at Handshake.Sequence._packetToError (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:202:8)
    at /home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
    at Pool.promiseCallback (/home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
    at /home/pooldaemon/nodejs-pool/lib/payment_systems/aeon.js:177:26
    at Array.forEach (native)
    at /home/pooldaemon/nodejs-pool/lib/payment_systems/aeon.js:173:14
    at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
2017-12-15 09:56 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: ER_CON_COUNT_ERROR: Too many connections
    at Handshake.Sequence._packetToError (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:202:8)
    at /home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
    at Pool.promiseCallback (/home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
    at /home/pooldaemon/nodejs-pool/lib/payment_systems/aeon.js:177:26
    at Array.forEach (native)
    at /home/pooldaemon/nodejs-pool/lib/payment_systems/aeon.js:173:14
    at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
`

**Comment by Snipa22** [comment]
Provide useful information, not a pure log dump.
