### ISSUE TITLE
worker module crashing, multiple errors

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#213]
```
2|worker   |     at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
2|worker   |     at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
2|worker   |     at emitOne (events.js:96:13)
2|worker   |     at Request.emit (events.js:188:7)
2|worker   |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
2|worker   |     at emitOne (events.js:96:13)
2|worker   |     at ClientRequest.emit (events.js:188:7)
2|worker   |     at Socket.socketErrorListener (_http_client.js:310:9)
2|worker   |     at emitOne (events.js:96:13)
2|worker   |     at Socket.emit (events.js:188:7)
2|worker   |     at emitErrorNT (net.js:1278:8)
2|worker   |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2|worker   |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2|worker   | 2017-12-18 01:09 +00:00: Unable to get wallet stats: Unable to process balance
2|worker   | 2017-12-18 01:10 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

2|worker   | 2017-12-18 01:10 +00:00: Unable to get wallet stats: Unable to process balance
2|worker   | 2017-12-18 01:11 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2|worker   | 2017-12-18 01:11 +00:00: Unable to get wallet stats: Unable to process balance
2|worker   | 2017-12-18 01:11 +00:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|worker   | Issue in getting block header.  Skipping node monitor
2|worker   | 2017-12-18 01:12 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2|worker   | 2017-12-18 01:12 +00:00: TypeError: Cannot read property 'block_header' of undefined
2|worker   |     at /home/pooldaemon/nodejs-pool/lib/worker.js:448:31
2|worker   |     at /home/pooldaemon/nodejs-pool/lib/support.js:100:24
2|worker   |     at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
2|worker   |     at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
2|worker   |     at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
2|worker   |     at emitOne (events.js:96:13)
2|worker   |     at Request.emit (events.js:188:7)
2|worker   |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
2|worker   |     at emitOne (events.js:96:13)
2|worker   |     at ClientRequest.emit (events.js:188:7)
2|worker   |     at Socket.socketErrorListener (_http_client.js:310:9)
2|worker   |     at emitOne (events.js:96:13)
2|worker   |     at Socket.emit (events.js:188:7)
2|worker   |     at emitErrorNT (net.js:1278:8)
2|worker   |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2|worker   |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2|worker   | 2017-12-18 01:12 +00:00: Database Worker: LMDB Env Initialized.
2|worker   | 2017-12-18 01:12 +00:00: Unable to get wallet stats: Unable to process balance
```

It was working fine, had to reboot the server and now the worker module is restarting every 2 minutes (manually closed all pool services and monerod before rebooting).

Tried restarting the monero service (sudo service monero restart) and restarting all modules (pm2 restart all). Only the worker module is showing errors, the others are fine.

Any help?

Thanks

**Comment by vitorgatti** [comment]
using the latest pool code, btw

**Comment by vitorgatti** [comment]
nevermind, restarted everything again and it's working fine... go figure.

**Comment by vitorgatti** [comment]
Nope, still happening:

```
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:45 +00:00: Processed 6/40/0/46 Trusted/Validated/Invalid/Total shares in the last 30 seconds
10|worker  | 2017-12-18 01:45 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
10|worker  | 2017-12-18 01:45 +00:00: Block headers identical to historical header.  Ignoring
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
9|blockMan | 2017-12-18 01:45 +00:00: Performing PPS payout on block: 1467073 Block Value: 5.848087513046
9|blockMan | 2017-12-18 01:45 +00:00: PPS payout cycle complete on block: 1467073 Block Value: 5.848087513046 Block Payouts: 0 Payout Percentage: 0%
9|blockMan | Scan complete, unlocking remainder of blockManager functionality.
14|pool    | 2017-12-18 01:45 +00:00: Performing difficulty update on miners
14|pool    | 2017-12-18 01:45 +00:00: Performing difficulty update on miners
14|pool    | 2017-12-18 01:45 +00:00: Performing difficulty update on miners
14|pool    | 2017-12-18 01:45 +00:00: Performing difficulty update on miners
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:45 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:46 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
14|pool    | 2017-12-18 01:46 +00:00: Processed 5/36/0/41 Trusted/Validated/Invalid/Total shares in the last 30 seconds
14|pool    | 2017-12-18 01:46 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
10|worker  | 2017-12-18 01:46 +00:00: TypeError: Cannot read property 'block_header' of undefined
10|worker  |     at /home/pooldaemon/nodejs-pool/lib/worker.js:448:31
10|worker  |     at /home/pooldaemon/nodejs-pool/lib/support.js:100:24
10|worker  |     at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
10|worker  |     at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
10|worker  |     at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
10|worker  |     at emitOne (events.js:96:13)
10|worker  |     at Request.emit (events.js:188:7)
10|worker  |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
10|worker  |     at emitOne (events.js:96:13)
10|worker  |     at ClientRequest.emit (events.js:188:7)
10|worker  |     at Socket.socketErrorListener (_http_client.js:310:9)
10|worker  |     at emitOne (events.js:96:13)
10|worker  |     at Socket.emit (events.js:188:7)
10|worker  |     at emitErrorNT (net.js:1278:8)
10|worker  |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
10|worker  |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
PM2        | App [worker] with id [10] and pid [29156], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:worker id:10
PM2        | App name:worker id:10 online
14|pool    | 2017-12-18 01:46 +00:00: (Master) Queue debug state: 0 items in the queue 1 items being processed
10|worker  | 2017-12-18 01:46 +00:00: Database Worker: LMDB Env Initialized.
14|pool    | 2017-12-18 01:46 +00:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
```

Any help appreciated. Thanks

**Comment by vitorgatti** [comment]
this was caused by one of the latest commits, restored my nodejs-pool backup folder and the worker module is not crashing anymore.

@Snipa22 could you please take a look? thanks

**Comment by Snipa22** [comment]
All current comments are stable and working.  Something on your side must be breaking.  I've been running a test pool for several days with no issues.  Most likely, something's broken in your monerod.

**Comment by vitorgatti** [comment]
will take a look then, thank you

**Comment by ArqTras** [comment]
aeond storing file.
use aeond --rpc-bind-ip 127.0.0.1 --rpc-bind-port 11181 **--disable-save**

**Comment by Bathmat** [comment]
fix for this issue: https://github.com/Snipa22/nodejs-pool/issues/412
