### ISSUE TITLE
EPIPE Error

### ISSUE THREAD

**Issue by jredwine2857** [Snipa22/nodejs-pool#216]
Getting lots of npm logs on the nodejs-pool folder.  No mining ports are listening either.  Though web and API's seem to be both listening and working.  This is on AWS Ubuntu 16.04, brand new build.

0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v6.9.2/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v6.9.2/bin/npm',
1 verbose cli   'ls',
1 verbose cli   '--json',
1 verbose cli   '--production' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose exit [ 0, true ]
5 verbose stack Error: write EPIPE
5 verbose stack     at exports._errnoException (util.js:1022:11)
5 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
6 verbose cwd /home/ubuntu/nodejs-pool
7 error Linux 4.4.0-1041-aws
8 error argv "/home/ubuntu/.nvm/versions/node/v6.9.2/bin/node" "/home/ubuntu/.n$
9 error node v6.9.2
10 error npm  v3.10.9
11 error code EPIPE
12 error errno EPIPE

**Comment by jredwine2857** [comment]
In case someone else has this same issue.  Mine was resolved by changing the pool ID from 0 to 1.  I finally figured this out after looking the pool/pm2 error log here: /home/ubuntu/.pm2/logs/pool-error-7.log .

I also changed bind IP to 0.0.0.0 instead of my external, tho I still testing to make sure that's correct as it deviates from what's in the readme.
