### ISSUE TITLE
long-runner error

### ISSUE THREAD

**Issue by mtompkins** [Snipa22/nodejs-pool#217]
2017-12-20 09:51 -05:00: Error: You specified keyIsUint32 on the Dbi, so you can't use other key types with it.
    at /home/monero/nodejs-pool/lib/local_comms.js:638:46
    at Array.forEach (<anonymous>)
    at /home/monero/nodejs-pool/lib/local_comms.js:630:45
    at nextTask (/home/monero/nodejs-pool/node_modules/async/dist/async.js:5070:14)
    at /home/monero/nodejs-pool/node_modules/async/dist/async.js:5064:13
    at apply (/home/monero/nodejs-pool/node_modules/async/dist/async.js:21:25)
    at /home/monero/nodejs-pool/node_modules/async/dist/async.js:56:12
    at /home/monero/nodejs-pool/node_modules/async/dist/async.js:840:16
    at /home/monero/nodejs-pool/lib/local_comms.js:605:29
    at /home/monero/nodejs-pool/lib/coins/xmr.js:70:24
    at /home/monero/nodejs-pool/lib/support.js:103:20
    at Object.parseBody (/home/monero/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/monero/nodejs-pool/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/home/monero/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/home/monero/nodejs-pool/node_modules/request-json/node_modules/request/request.js:1044:10)

**Comment by mtompkins** [comment]
Trying to add a little info - if I delete `pool_db` so as to have a clean starting point, the error occurs very quickly so it is reproducible

**Comment by ArqTras** [comment]
Try to run deploy bash again

**Comment by mtompkins** [comment]
@ArqTras TY - I have a couple times, stepping through each line in fact. The compilation exists without issue. It's only when running the task that the error is thrown. Happy to provide more info on request.

**Comment by ArqTras** [comment]
"cryptonote-util": "git://github.com/Snipa22/node-cryptonote-util.git#xmr-Nan-2.0",

**Comment by mtompkins** [comment]
That source fails to compile as I've indicated in the referenced issue.

**Comment by bobbieltd** [comment]
#225 Do any one find the cause and solution for this error ? I run manually deploys.bash with Aeon without errors.

**Comment by mtompkins** [comment]
It is worth noting that I am using Apache and not Caddy in the installation. Perhaps that's part of the cause.

**Comment by Ogy** [comment]
same problem

**Comment by ArqTras** [comment]
check libboost version and also
shareHost in sql 
http://127.0.0.1:8000/leafApi

**Comment by Ogy** [comment]
hi 
i have up-to-date 16.04 ubuntu
libboost-all-dev/xenial,now 1.58.0.1ubuntu1 amd64 [installed]

$ mysql pool -s -e"select * from config where item='shareHost';"
id	module	item	item_value	item_type	Item_desc
132	general	shareHost	http://127.0.0.1:8000/leafApi	string	Host that receives share information


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by Ogy** [comment]
this is the last longRunners OK log
6|longRunn | 2017-12-26 03:19 +01:00: Scanning from: 1472894 for more than: 152815644467 shares

**Comment by mtompkins** [comment]
I've tried with `boost` 1.58 compiled from source on 16.04 as well as 1.62 from `apt` on a 17.10 box

**Comment by bobbieltd** [comment]
@ArqTras For config.json, can I leave bind IP : “127.0.0.1” and hostname : “testpool.com” ? What are these for ? Is it for “leaf installation” and multi-server ?

**Comment by ArqTras** [comment]
If single pool use 0.0.0.0 and place domain name

**Comment by Ogy** [comment]
https://github.com/Snipa22/nodejs-pool/issues/227

**Comment by Ogy** [comment]
#https://github.com/Snipa22/nodejs-pool/issues/227

**Comment by Ogy** [comment]
#227

**Comment by Ogy** [comment]
mdb_stat -fear ~/pool_db/   now shows 571 readers
and longrunner now dying on  Error: MDB_READERS_FULL: Environment maxreaders limit reached

**Comment by ArqTras** [comment]
Join https://discordapp.com/invite/vGeRWQF
Ping me at PM mayby I can help

**Comment by bobbieltd** [comment]
I find the problem. It’s from NVM comptability. Just downgrade NVM to 6.9.2 or make new installation with old deploy.bash . See this #230

**Comment by mtompkins** [comment]
I confirm reverting to the earlier version of node, specifically 6.9.2 as per @bobbieltd does resolve the error. See #230

**Comment by Ogy** [comment]
Error: You specified keyIsUint32 on the Dbi
i still have this error even on 6.9.2 code

**Comment by bobbieltd** [comment]
@Ogy Yes, Snipa and other developers are modifying the code and it doesn’t work yet. The code is not the same at this time. You should wait for Snipa to correct it or try the suggested code at the lastest commit.

**Comment by bobbieltd** [comment]
AdrvDov suggested : 
blockID = Number((blockID - lastBlock+1) * -1); // don't work

try

for (let found = (cursor.goToRange(parseInt(blockID)) === blockID); found; found = cursor.goToNextDup()) {

**Comment by CoinLogik** [comment]
Trying decipher what the actual cause is here. Can someone explain? My Ubuntu 16 VM has AES, `shareHost` is set.

**Comment by mxjoe** [comment]
Got the same problem here.

7|longRunn | 2018-01-09 14:28 +00:00: Error: You specified keyIsUint32 on the Dbi, so you can't use other key types with it.
7|longRunn |     at Error (native)
7|longRunn |     at /home/user/nodejs-pool/lib/local_comms.js:638:46
7|longRunn |     at Array.forEach (native)
7|longRunn |     at /home/user/nodejs-pool/lib/local_comms.js:630:45
7|longRunn |     at nextTask (/home/user/nodejs-pool/node_modules/async/dist/async.js:5070:14)
7|longRunn |     at /home/user/nodejs-pool/node_modules/async/dist/async.js:5064:13
7|longRunn |     at apply (/home/user/nodejs-pool/node_modules/async/dist/async.js:21:25)
7|longRunn |     at /home/user/nodejs-pool/node_modules/async/dist/async.js:56:12
7|longRunn |     at /home/user/nodejs-pool/node_modules/async/dist/async.js:840:16
7|longRunn |     at /home/user/nodejs-pool/lib/local_comms.js:605:29
7|longRunn |     at /home/user/nodejs-pool/lib/coins/xmr.js:70:24
7|longRunn |     at /home/user/nodejs-pool/lib/support.js:103:20
7|longRunn |     at Object.parseBody (/home/user/nodejs-pool/node_modules/request-json/main.js:74:12)
7|longRunn |     at Request._callback (/home/user/nodejs-pool/node_modules/request-json/main.js:148:26)
7|longRunn |     at Request.self.callback (/home/user/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
7|longRunn |     at emitTwo (events.js:106:13)

**Comment by mxjoe** [comment]
I created a pull request #260 which fixed the problem on my server.
