### ISSUE TITLE
No payments on PPLNS pool when block is found

### ISSUE THREAD

**Issue by lukaszmatczak** [Snipa22/nodejs-pool#223]
When my PPLNS pool finds a block no payments are made. Even miners balance isn't updated. In logs I see following error:
```2017-12-22 13:04 +01:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:185:7)
    at Handshake._onTimeout (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Pool.js:202:8)
    at /home/moneropool/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/home/moneropool/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/moneropool/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/moneropool/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
    at Pool.promiseCallback (/home/moneropool/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/home/moneropool/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
    at /home/moneropool/nodejs-pool/lib/blockManager.js:109:34
    at nextTask (/home/moneropool/nodejs-pool/node_modules/async/dist/async.js:5070:14)
    at /home/moneropool/nodejs-pool/node_modules/async/dist/async.js:5064:13
    at apply (/home/moneropool/nodejs-pool/node_modules/async/dist/async.js:21:25)
    at /home/moneropool/nodejs-pool/node_modules/async/dist/async.js:56:12
2017-12-22 13:04 +01:00: Unhandled rejection Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:185:7)
    at Handshake._onTimeout (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Pool.js:202:8)
    at /home/moneropool/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/home/moneropool/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/moneropool/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/moneropool/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
    at Pool.promiseCallback (/home/moneropool/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/home/moneropool/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
    at /home/moneropool/nodejs-pool/lib/blockManager.js:109:34
    at nextTask (/home/moneropool/nodejs-pool/node_modules/async/dist/async.js:5070:14)
    at /home/moneropool/nodejs-pool/node_modules/async/dist/async.js:5064:13
    at apply (/home/moneropool/nodejs-pool/node_modules/async/dist/async.js:21:25)
    at /home/moneropool/nodejs-pool/node_modules/async/dist/async.js:56:12
```

Everything other works OK. Is something wrong with configuration or with code?
Please help me
Thanks in advance

**Comment by jredwine2857** [comment]
Do you have wallet rpc running?  If so, is it running on the same machine?  If it's not you have to add a switch to bind it to 0.0.0.0 so it listens for remote connections.  Then you have another switch you have to out as confirmation of security concerns when binding to 0.0.0.0.  

Can't remember the switches off the top of my head and they aren't documented real well, but reply and I'll dig em up if you need em. 

Good luck!

**Comment by 1rV1N-git** [comment]
your blockmanager module don't have access to mysql
Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/moneropool/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:86:13)

**Comment by lukaszmatczak** [comment]
Thanks for your replies.

@jredwine2857 I have wallet on the same host, so I think it's not the reason.

@1rV1N-git It would be strange, because other modules on the same host can connect to MySQL without any problem.

**Comment by 1rV1N-git** [comment]
@lukaszmatczak The log what you show from bloackmanager-error.log?

this line seems like error from pool-error.log
 at Pool.getConnection (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/moneropool/nodejs-pool/node_modules/mysql/lib/Pool.js:202:8)

**Comment by lukaszmatczak** [comment]
@1rV1N-git Yes, it is from blockManager-error-1.log

**Comment by jredwine2857** [comment]
Did u get this working yet?  After re-reading the log it does appear to be mysql throwing the error.

**Comment by lukaszmatczak** [comment]
I've just switched to node-cryptonote-pool.
