### ISSUE TITLE
Errors installing via leaf.bash

### ISSUE THREAD

**Issue by mxjoe** [Snipa22/nodejs-pool#240]
When installing a leaf node via leaf.bash on Ubuntu 16.04 x64 minimal it shows some errors while installing.

Computing checksum with sha256sum
Checksums matched!
Now using node v8.9.3 (npm v5.5.1)
Creating default alias: default -> v8.9.3
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated jssha@1.6.0: jsSHA versions < v2.0.0 will no longer receive features
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

`>` bignum@0.12.5 install /home/user/nodejs-pool/node_modules/bignum
`>` node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@8.9.3 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

[...]

In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from ../cryptonight.c:13:
../cryptonight.c: In function ‘ExpandAESKey256_sub2’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^
../cryptonight.c:71:7: error: called from here
  tmp4 = _mm_aeskeygenassist_si128(*tmp1, 0x00);
       ^
multihashing.target.mk:115: recipe for target 'Release/obj.target/multihashing/cryptonight.o' failed
make: *** [Release/obj.target/multihashing/cryptonight.o] Error 1
make: Leaving directory '/home/user/nodejs-pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-042stab125.5
gyp ERR! command "/home/user/.nvm/versions/node/v8.9.3/bin/node" "/home/user/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/nodejs-pool/node_modules/multi-hashing
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

`>` node-lmdb@0.4.12 install /home/user/nodejs-pool/node_modules/node-lmdb
`>` node-gyp rebuild

[...]

`>>>` Executing systemctl enable pm2-user
Created symlink from /etc/systemd/system/multi-user.target.wants/pm2-user.service to /etc/systemd/system/pm2-user.service.
[DONE] 
`>>>` Executing systemctl start pm2-user
Job for pm2-user.service failed because the control process exited with error code. See "systemctl status pm2-user.service" and "journalctl -xe" for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-user failed, see error above.
Installing pm2-logrotate in the background!
You're setup with a leaf node!  Congrats
user@xmr-us:~$ [PM2] Spawning PM2 daemon with pm2_home=/home/user/.pm2
[PM2] PM2 Successfully daemonized
[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Calling [NPM] to install pm2-logrotate ...
`+` pm2-logrotate@2.4.0
added 260 packages in 13.553s
[PM2][Module] Module downloaded
[PM2][WARN] Applications pm2-logrotate not running, starting...
[PM2] App [pm2-logrotate] launched (1 instances)
[PM2][Module] Monitoring module behavior for potential issue (5secs...)

**Comment by jredwine2857** [comment]
I know there have been some issues reported with node v8.9.3.  Several other post have said using v6.9.2 works.   I can't say for sure it does as I am both getting the same Int message in the longRunner logs and my leaf node still doesn't work, but what I did was fork Snipa's and edit the bash files, replacing everything that said v8.9.3 with v6.9.2.   Worth a shot I guess if you want to try it.

**Comment by ArqTras** [comment]
https://github.com/ArqTras/nodejs-pool/wiki/Leaf-Node-Wiki
It is for aeon but can be modified o use monero or aeon or etn

**Comment by mxjoe** [comment]
@ArqTras Thanks for the Wiki, I will have a look at it! But at first I need a new server provider as my former US provider has had several downtimes so far.
