### ISSUE TITLE
ETN pool : money in pool wallet but no payment to miners and api owed error

### ISSUE THREAD

**Issue by bobbieltd** [Snipa22/nodejs-pool#251]
We setup an ETN pool. The pool found 5 blocks and got ETN in pool wallet. However, no payment made and api got following errors : 
2018-01-03 16:28 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'owed' of undefined
    at /home/pooldaemon/nodejs-pool/lib/api.js:592:44
    at Array.forEach (native)
    at /home/pooldaemon/nodejs-pool/lib/api.js:591:22
    at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
2018-01-03 16:30 +00:00: Unhandled rejection TypeError: Cannot read property 'owed' of undefined
    at /home/pooldaemon/nodejs-pool/lib/api.js:592:44
    at Array.forEach (native)

The other modules don’t have any particular error log.
I think api doesn't concern the payment but I don't know why it got errors with stats.
The main problem is that miners don't got paid. I can see them in balance table but ETNs are alway in the pool wallet. Can anyone help ?

**Comment by CoinLogik** [comment]
Check your `balance` table in MySQL.


This is the line in question:
https://github.com/Snipa22/nodejs-pool/blob/master/lib/api.js#L592
```
intCache[row.pool_type].owed += row.amount;
```

If would seem that there is a row in `balance` table where `pool_type` is wrong/bad because it doesn't match types in `intCache` variable.

With intCache defined as:
```
let intCache = {
        'pplns': {owed: 0, paid: 0, mined: 0, shares: 0, targetShares: 0},
        'pps': {owed: 0, paid: 0, mined: 0, shares: 0, targetShares: 0},
        'solo': {owed: 0, paid: 0, mined: 0, shares: 0, targetShares: 0},
        'global': {owed: 0, paid: 0, mined: 0, shares: 0, targetShares: 0},
        'fees': {owed: 0, paid: 0, mined: 0, shares: 0, targetShares: 0}
    };
```

**Comment by ArqTras** [comment]
CoinLogik
Can you enter your solution https://github.com/ArqTras/nodejs-pool
We'll test it.

**Comment by CoinLogik** [comment]
@ArqTras I have no real solution as I don't know what's in @bobbieltd's DB or the contextual info, just offered some debugging advice.

**Comment by bobbieltd** [comment]
Sorry, I forgot to tell that I checked balance database and it’s fine. All tables in database are fine. The code is based in ArqTras’s repo.

**Comment by bobbieltd** [comment]
pool_type is fees or pplns in balance. Nothing is abnormal. Amount variables are fine too.

**Comment by bobbieltd** [comment]
@ArqTras It’s not the same error but quite similar. Take a look at this https://github.com/Snipa22/nodejs-pool/issues/61

**Comment by ArqTras** [comment]
Working with new update https://github.com/ArqTras/nodejs-pool 
Thanks to @bobbieltd for cooperation

**Comment by bobbieltd** [comment]
@ArqTras I think the pool that got these errors because the fee addresses were removed and api could't calculate. I don't encounter any errors with api. Look at the way you digged the config, I can see you will progress very fast. Thanks to you again, I can setup an ETN pool. I close this issue because it does not happen with ArqTras' repo. You guys can try install ETN pool with ArqTras.
