### ISSUE TITLE
Problem with nodejs-pool as pool software for krb

### ISSUE THREAD

**Issue by yekn0m** [Snipa22/nodejs-pool#261]
Can't get Nodejs Pool working with KRB:

I installed the pool manually (step by step as in the deployment script for xmr). 
All went fine and all processes are starting. 
But when i connect a miner to one of the ports, the proccess (I think worker) crashes (only the port). 
In the error logfiles from the worker i get logs like

--

2018-01-09 02:44 +00:00: Error: Failed to parse block
    at Coin.convertBlob (/home/pool/nodejs-pool.krb/lib/coins/krb.js:87:23)
    at Coin.BlockTemplate.nextBlob (/home/pool/nodejs-pool.krb/lib/coins/krb.js:140:37)
    at Miner.getJob (/home/pool/nodejs-pool.krb/lib/pool.js:479:48)
    at handleMinerData (/home/pool/nodejs-pool.krb/lib/pool.js:698:28)
    at handleMessage (/home/pool/nodejs-pool.krb/lib/pool.js:898:13)
    at Socket.<anonymous> (/home/pool/nodejs-pool.krb/lib/pool.js:956:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
2018-01-09 02:44 +00:00: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Worker.send (internal/cluster/worker.js:54:28)
    at /home/pool/nodejs-pool.krb/lib/pool.js:127:16
    at Array.forEach (<anonymous>)
    at sendToWorkers (/home/pool/nodejs-pool.krb/lib/pool.js:126:16)
    at /home/pool/nodejs-pool.krb/lib/pool.js:167:21
    at /home/pool/nodejs-pool.krb/lib/coins/krb.js:69:20
    at /home/pool/nodejs-pool.krb/lib/support.js:103:20
    at Object.parseBody (/home/pool/nodejs-pool.krb/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pool/nodejs-pool.krb/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/home/pool/nodejs-pool.krb/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/pool/nodejs-pool.krb/node_modules/request-json/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)

--

I have no idea where to start to fix it.

I tried different cryponote-utils. Most didn't compile (Ubuntu LTS). One works, connection works too, but all shares are rejected. So this wasn't jet a solution.
I even tried to say in the config file, its xmr and not krb, but then the miner couldn't connect (invalid hash address ;))

My Config is Ubuntu LTS, Karbo Simplewallet, Karbowanecd, newest nodejs-pool (from git), Modules, nodejs etc as in the deployment bash script.

**Comment by ArqTras** [comment]
Check:
1. ip and ports of daemon on sql and on your ktb d
2. config.json and is there krb ? and 0.0.0.0
3. Remove from ports 9000 ssl whole row, stay at 3333 5555 7777 standard ports

**Comment by yekn0m** [comment]
Hmm
as i stated bevor, with different cryptonote-utils it is working with slow miner,
Webui etc works, connections are all right.

I never changed the config.json between working/testing/crash etc.

Only with krb in the config it crashs (or works),with xmr comes the msg wrong hash (or so)

Didn't usw ssl, Ports are different, thats right, but why should this be the problem (they are nowhere fix coded) But to be shure, i'll test it.

I think it is a combination of cryptonote-utils (from snippa), the pool and krb..

**Comment by bobbieltd** [comment]
Even though I think 90% that it won't work. But why not, give it a try:
"cryptonote-util": "git://github.com/Snipa22/node-cryptonote-util.git#xmr-Nan-2.0",
change this to mine
"cryptonote-util": "git://github.com/bobbieltd/node-cryptonote-util.git#xmr-Nan-2.0",

**Comment by yekn0m** [comment]
@bobbieltd I tried your repository and there is a different error in the worker error logfile, when I connect a miner to one of the ports:

`
2018-01-11 14:40 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2018-01-11 14:40 +00:00: Issue in getting block header.  Skipping node monitor
2018-01-11 14:40 +00:00: TypeError: Cannot read property 'block_header' of undefined
    at /home/pool/nodejs-pool.krb/lib/worker.js:448:32
    at /home/pool/nodejs-pool.krb/lib/support.js:100:24
    at Object.parseBody (/home/pool/nodejs-pool.krb/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pool/nodejs-pool.krb/node_modules/request-json/main.js:148:26)
    at self.callback (/home/pool/nodejs-pool.krb/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pool/nodejs-pool.krb/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2018-01-11 14:41 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2018-01-11 14:41 +00:00: TypeError: Cannot read property 'block_header' of undefined
    at /home/pool/nodejs-pool.krb/lib/worker.js:448:32
    at /home/pool/nodejs-pool.krb/lib/support.js:100:24
    at Object.parseBody (/home/pool/nodejs-pool.krb/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pool/nodejs-pool.krb/node_modules/request-json/main.js:148:26)
    at self.callback (/home/pool/nodejs-pool.krb/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pool/nodejs-pool.krb/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

`

**Comment by yekn0m** [comment]
One thing with the cryptonight-utils from @bobbieltd and @Snipa22 is, that the worker crashes, but immediately restarts with the specific port.

**Comment by bobbieltd** [comment]
My advice : Forget this Karbo and setup pool with XMR. Or you have some coders to help you. It’s pain to manage with other coins than XMR.

**Comment by bobbieltd** [comment]
@yekn0m Are you successful with setinh up your pool ?

**Comment by yekn0m** [comment]
cryptonote-utils from https://github.com/pinkflozd/node-cryptonote-util and https://github.com/sx5486510/node-cryptonote-util are working a little bit ;)

The other cryptonote-utils have newer code/hashing or are for xmr optimized (as it seems)

Small miner (cpu) have no rejected shares, faster nearly every share is rejected. 
With 
-  wrong id (id is much to old, not cached),
- difficulty to low: wrong error text, because the real reason is wrong hash from cryptonote function compared to submitted hash (not trusted share => compare...) 

Changing the number of cached ids didn't help, reducing the time for share (targetTime?) to 15 sec or increasing to 60 didn't help either. 
Next days I'll try to increase it higher.. (on a test forkenote pool it is at about 160sec)

**Comment by ArqTras** [comment]
Remove ssl port from database pool ports 9000 
Wait for full daemon sync

**Comment by bobbieltd** [comment]
@yekn0m You are going to quite right direction. Keep trying, you’ll be able to setup KRB pool in a week. I need to test my theory first and keep you in touch.

**Comment by bobbieltd** [comment]
@yekn0m Did you try git://github.com/forknote/node-cryptonote-util.git ?

**Comment by bobbieltd** [comment]
@yekn0m Try if you haven't :         "multi-hashing": "git://github.com/fancoder/node-multi-hashing.git",
        "cryptonote-util": "git://github.com/forknote/node-cryptonote-util.git"

**Comment by bobbieltd** [comment]
@yekn0m I’d like to form a partnership with your KRB pool (on a condition : you’ll never setup AEON, ETN or INTENSECOIN pool and I’ll never setup KRB pool to avoid direct conflict of interest ). I’ll provide my assistance and we can exhange our experiences. If it rings a bell, contact me.

**Comment by yekn0m** [comment]
@bobbieltd I'm interessted, but at the moment not much time for further research in the problem and the pool etc. 
Hopefully next week will be better, then I'll contact you..

**Comment by bobbieltd** [comment]
@yekn0m Send me a way of chatting with you to email : support@mail.semipool.com
