### ISSUE TITLE
Error: MDB_READERS_FULL: Environment maxreaders limit reached

### ISSUE THREAD

**Issue by SmartGuyz** [Snipa22/nodejs-pool#266]
I have the following error in remoteShare-error.log:

2018-01-11 12:28 +00:00: Error: MDB_READERS_FULL: Environment maxreaders limit reached
    at /home/pooldaemon/nodejs-pool/lib/local_comms.js:238:54
    at Array.forEach (<anonymous>)
    at Database.storeBulkShares (/home/pooldaemon/nodejs-pool/lib/local_comms.js:192:21)
    at Timeout.storeShares [as _onTimeout] (/home/pooldaemon/nodejs-pool/lib/remoteShare.js:76:25)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

Also it restarts all the time, is this normal?

**Comment by SmartGuyz** [comment]
Also I got this error, but I cannot find any value that is false:

2018-01-11 14:21 +00:00: TypeError: Cannot create property 'fee' on boolean 'false'
    at /home/pooldaemon/nodejs-pool/lib/api.js:253:28
    at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at /home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:277:22
    at param (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:349:14)
    at param (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:410:3)
    at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/home/pooldaemon/nodejs-pool/node_modules/body-parser/lib/types/json.js:109:7)
    at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:312:13)
    at /home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:271:10)

**Comment by yekn0m** [comment]
I had once the first problem too, but after stopping all processes and restarting (or was it even rebooting) the problem was solved.
I think the second occurd once too, but puh.. at the moment no idea what the solution was

**Comment by vaibhavch** [comment]
@Snipa22  I am too getting `maxreaders limit reached ` frequently about every 20 mins.  Is it necessary to restart daemons every time?  Does it effect pool efficiency in any way (because i saw hashes from miners reinstating on every restart)?  is there any alternative workaround to solve this issue?
