### ISSUE TITLE
Error  in pool-error-8.log

### ISSUE THREAD

**Issue by Bousteur30** [Snipa22/nodejs-pool#269]
Hi,

After install deploy.bash and manual configuration, i start daemon and i have the following error in pool-error-8.log

 
`2018-01-17 10:00 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
2018-01-17 10:00 +00:00: TypeError: Cannot read property 'height' of undefined
    at Timeout._onTimeout (/home/pooldaemon/nodejs-pool/lib/pool.js:833:114)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2018-01-17 10:00 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined`

do you have an idea ?

**Comment by Bousteur30** [comment]
`global.mysql.query("UPDATE pools SET blockIDTime = now(), blockID = ? where id = ?", [activeBlockTemplate.height, global.config.pool_id]);`

**Comment by bobbieltd** [comment]
Look for bug or see the solution here #150 . I don’t understand why port 9000 triggers this issue.

**Comment by Bousteur30** [comment]
Thank you but how to remove port 9000 in database ?

**Comment by bobbieltd** [comment]
In mysql, pool.port_config , look for 9000, change ssl from 1 to 0.
Anyway, even with this error , your pool still works. SSL isn’t much important and I didn’t dig out how to put certificate for it.

**Comment by bobbieltd** [comment]
Now I think it’s a bug, I’ll make PR to fix it.
