### ISSUE TITLE
socket error while connecting miner

### ISSUE THREAD

**Issue by alexmateescu** [Snipa22/nodejs-pool#285]
Hi. 

I have setup your pool onto and i am getting the following error when i am trying to connect the miner. The error is below and the miner i use is xmr-stak. i have tried to replace cryptonote-util package and got it working with one of them but only for very very slow hash rate line ~19H/s. anything else the results are rejected. what could it be wrong? where should i look?

if i setup the pool on the cryptonote-universal-pool it is working and i was wondering if there could be something worng in the cryptonote-util package.

Regards

8|init | Error: Failed to parse block
8|init | at Object.BlockTemplate.nextBlob (/home/alex/node-cryptonote-pool/lib/pool.js:128:23)
8|init | at Object.Miner.getJob (/home/alex/node-cryptonote-pool/lib/pool.js:301:41)
8|init | at handleMinerMethod (/home/alex/node-cryptonote-pool/lib/pool.js:511:28)
8|init | at handleMessage (/home/alex/node-cryptonote-pool/lib/pool.js:645:13)
8|init | at Socket.socket.on.on.on.pushMessage (/home/alex/node-cryptonote-pool/lib/pool.js:699:25)
8|init | at Socket.emit (events.js:95:17)
8|init | at Socket. (stream_readable.js:765:14)
8|init | at Socket.emit (events.js:92:17)
8|init | at emitReadable (_stream_readable.js:427:10)
8|init | at emitReadable (_stream_readable.js:423:5)
8|init | Error: Failed to parse block
8|init | at Object.BlockTemplate.nextBlob (/home/alex/node-cryptonote-pool/lib/pool.js:128:23)
8|init | at Object.Miner.getJob (/home/alex/node-cryptonote-pool/lib/pool.js:301:41)
8|init | at handleMinerMethod (/home/alex/node-cryptonote-pool/lib/pool.js:511:28)
8|init | at handleMessage (/home/alex/node-cryptonote-pool/lib/pool.js:645:13)
8|init | at Socket.socket.on.on.on.pushMessage (/home/alex/node-cryptonote-pool/lib/pool.js:699:25)
8|init | at Socket.emit (events.js:95:17)
8|init | at Socket. (stream_readable.js:765:14)
8|init | at Socket.emit (events.js:92:17)
8|init | at emitReadable (_stream_readable.js:427:10)
8|init | at emitReadable (_stream_readable.js:423:5)
8|init | 2018-01-29 09:29:32 [master] Pool fork 1 died, spawning replacement worker...
8|init | 2018-01-29 09:29:34 [pool] (Thread 1) New block to mine at height 4014 w/ difficulty of 168679209

**Comment by lloyd-yeo** [comment]
Did anyone find a resolution to this error?

I'm also getting this after running pm2 log pool:

/home/pooldaemon/.pm2/logs/pool-error-8.log last 15 lines:
8|pool     | 2018-02-10 09:56 +00:00: (Worker 2 - 23825) Socket Error from 88.98.201.182 Error: Error: read EHOSTUNREACH
8|pool     | 2018-02-10 10:18 +00:00: (Worker 4 - 23835) Socket Error from 202.166.49.253 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 10:24 +00:00: (Worker 3 - 23830) Duplicate share: {"id":"e755750c-b444-48f9-bbb7-06b13d6f435d","job_id":"635M+dZkfsl71YwF0NqfraOvelbz","nonce":"c0300000","result":"a3a9f4e35caf239d028c6df29b1979f4649c0db8233de6bd3e6b6fc730623f00"} from 48WCGXaoL7gUY8fwSxUPgR4VYx4iVTJYEF4jP7Uq4jG26Hz9Gc6QjgU1m7Hht5pBPJbccCyR4khkZD88wSwErkRt2FkmpNH ID: a.cole.f@gmail.com IP: 174.102.10.144
8|pool     | 2018-02-10 10:31 +00:00: (Worker 3 - 23830) Socket Error from 58.182.37.57 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 10:40 +00:00: (Worker 2 - 23825) Socket Error from 116.87.88.44 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 10:40 +00:00: (Worker 1 - 23824) Socket Error from 60.50.46.95 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 11:02 +00:00: (Worker 4 - 23835) Malformed message from 5.101.40.34 Message: /*�Cookie: mstshash=Administr
8|pool     | 2018-02-10 11:06 +00:00: (Worker 3 - 23830) Socket Error from 202.166.49.253 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 11:15 +00:00: (Worker 1 - 23824) Socket Error from 119.74.138.124 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 11:18 +00:00: (Worker 3 - 23830) Socket Error from 222.164.18.235 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 11:24 +00:00: (Worker 3 - 23830) Malformed message from 5.101.40.34 Message: /*�Cookie: mstshash=Administr
8|pool     | 2018-02-10 11:28 +00:00: (Worker 2 - 23825) Socket Error from 202.166.49.253 Error: Error: read ETIMEDOUT
8|pool     | 2018-02-10 11:42 +00:00: (Worker 3 - 23830) Malformed message from 5.101.40.34 Message: /*�Cookie: mstshash=Administr

And for a known fact those IPs do not have any network issues. Might there be some sort of overloading?

**Comment by bobbieltd** [comment]
@alexmateescu  Coin not supported
@lloyd-yeo ETIMEOUT is normal.

**Comment by alexmateescu** [comment]
@bobbieltd i have also tried your node-cryptonote-util package and with that one with slow hash rate everything is fine but over 500 H/s it is rejecting all results. our coind looks like it is using v3 blocks. maybe if you could help fixing your cryptonote-util package. i am available to test and i can give you full access to the vm so test and fix.

**Comment by bobbieltd** [comment]
Could you please wait ? The nodejs-pool for forknote (ITNS) from one pool owner will be released open source soon. It’s not just util package, the codes are heavily modified and improved for ITNS (I think it will work flawlessssly with other forknote coins too).

**Comment by alexmateescu** [comment]
I can wait as i already have a pool working it is just that i like that one and would like to implement it.
Do you know when it will be released?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Learner <notifications@github.com> Date: 11/02/2018  06:15  (GMT+00:00) To: Snipa22/nodejs-pool <nodejs-pool@noreply.github.com> Cc: alexmateescu <alex.mateescu34@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Snipa22/nodejs-pool] socket error while connecting miner (#285) 
Could you please wait ? The nodejs-pool for forknote (ITNS) from one pool owner will be released open source soon. It’s not just util package, the codes are heavily modified and improved for ITNS (I think it will work flawlessssly with other forknote coins too).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Snipa22/nodejs-pool","title":"Snipa22/nodejs-pool","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Snipa22/nodejs-pool"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bobbieltd in #285: Could you please wait ? The nodejs-pool for forknote (ITNS) from one pool owner will be released open source soon. It’s not just util package, the codes are heavily modified and improved for ITNS (I think it will work flawlessssly with other forknote coins too)."}],"action":{"name":"View Issue","url":"https://github.com/Snipa22/nodejs-pool/issues/285#issuecomment-364725453"}}}

**Comment by bobbieltd** [comment]
For info, here is recently released ITNS (forknote) nodejs-pool for everyone from Venthos : https://github.com/Venthos/nodejs-pool

**Comment by alexmateescu** [comment]
thanks

i'll check it out
