### ISSUE TITLE
Config table not found

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#293]
I re-formatted my server with Ubuntu 17.04 LTS.  I installed MySQL 5.7.21, created the pool DB and the pool user.  I run the bash script and get the following error at the end:
 Use `pm2 show <id|name>` to get more details about an app
fatal: destination path 'lmdb' already exists and is not an empty directory.
HEAD is now at 4d21543... ITS#8622 fix xcursor after cursor_del
make: Nothing to be done for 'all'.
mkdir: cannot create directory ‘/home/pooldaemon/.bin’: File exists
Please run source ~/.bashrc to initialize the new LMDB tools.  Thanks for flying Snipa22 Patch Services.
Unhandled rejection Error: ER_NO_SUCH_TABLE: Table 'pool.config' doesn't exist
    at Query.Sequence._packetToError (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)

when I connect to mysql;
mysql> connect pool;
Connection id:    265
Current database: pool

mysql> show tables;
Empty set (0.00 sec)

**Comment by Snipa22** [comment]
WHy are you using 17.04?  Use 16.04 like it says in the guides.
