### ISSUE TITLE
Which MySQL version needs to be installed?

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#304]
I installed the current version of MySQL and had to reinstall everything.  Which version of MySQL should be installed?

**Comment by bobbieltd** [comment]
It is installed by sudo apt-get ( for Ubuntu 16.04 ). So it seems the latest version at the time of installation.

**Comment by snoski3** [comment]
@bobbieltd 
. I installed MySQL 5.7.21, created the pool DB and the pool user. I run the bash script and get the following error at the end:
Use pm2 show <id|name> to get more details about an app
fatal: destination path 'lmdb' already exists and is not an empty directory.
HEAD is now at 4d21543... ITS#8622 fix xcursor after cursor_del
make: Nothing to be done for 'all'.
mkdir: cannot create directory ‘/home/pooldaemon/.bin’: File exists
Please run source ~/.bashrc to initialize the new LMDB tools. Thanks for flying Snipa22 Patch Services.
Unhandled rejection Error: ER_NO_SUCH_TABLE: Table 'pool.config' doesn't exist
at Query.Sequence._packetToError (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
at Query.ErrorPacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
at Protocol._parsePacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)

**Comment by bobbieltd** [comment]
I can’t understand much but the way you run again the bash looks not the good way. 
The script install mysql for you, you don’t need to install by yourself. I’m not sure about backward comptability of mysql. I guess you don’t use Ubuntu 16.04.

**Comment by BKdilse** [comment]
I had the same issue when I 1st did a pool install a while back.  Do not install MySQL, let the install script do it, as it needs to know what the password is.

**Comment by TimeTravelersHackedMe** [comment]
I'm using the latest version of MariaDB and that's working fine

**Comment by snoski3** [comment]
I have confirmed that the current version works if you have the script install MySQL
