### ISSUE TITLE
Mysql Problem

### ISSUE THREAD

**Issue by isaack0815** [Snipa22/nodejs-pool#308]
Hay,
after the Install i have this error:

> 0|api      | 2018-02-12 19:44 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|api      | Error: ER_NO_SUCH_TABLE: Table 'pool.config' doesn't exist
0|api      |     at Query.Sequence._packetToError (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
0|api      |     at Query.ErrorPacket (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
0|api      |     at Protocol._parsePacket (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
0|api      |     at Parser.write (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
0|api      |     at Protocol.write (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
0|api      |     at Socket.<anonymous> (/home/node/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
0|api      |     at emitOne (events.js:116:13)
0|api      |     at Socket.emit (events.js:211:7)
0|api      |     at addChunk (_stream_readable.js:263:12)
0|api      |     at readableAddChunk (_stream_readable.js:250:11)
0|api      |     at Socket.Readable.push (_stream_readable.js:208:10)
0|api      |     at TCP.onread (net.js:594:20)
0|api      |     --------------------
0|api      |     at Pool.query (/home/node/nodejs-pool/node_modules/mysql/lib/Pool.js:199:23)
0|api      |     at /home/node/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
0|api      |     at Promise._execute (/home/node/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
0|api      |     at Promise._resolveFromExecutor (/home/node/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
0|api      |     at new Promise (/home/node/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
0|api      |     at Pool.promiseCallback (/home/node/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
0|api      |     at pool.query (/home/node/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
0|api      |     at Object.<anonymous> (/home/node/nodejs-pool/init.js:21:14)
0|api      |     at Module._compile (module.js:635:30)
0|api      |     at Object.Module._extensions..js (module.js:646:10)
0|api      |     at Module.load (module.js:554:32)
0|api      |     at tryModuleLoad (module.js:497:12)
0|api      |     at Function.Module._load (module.js:489:3)
0|api      |     at Object.<anonymous> (/home/node/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/lib/ProcessContainerFork.js:80:21)
0|api      |     at Module._compile (module.js:635:30)
0|api      |     at Object.Module._extensions..js (module.js:646:10)

**Comment by bobbieltd** [comment]
Ubuntu version ?

**Comment by isaack0815** [comment]
Ubuntu 16.04
Mysql: mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

**Comment by isaack0815** [comment]
when i reinstall i have this error:
`Unhandled rejection Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'pool'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/node/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/node/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/node/nodejs-pool/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/node/nodejs-pool/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/node/nodejs-pool/node_modules/mysql/lib/Pool.js:202:8)
    at /home/node/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/home/node/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/node/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/node/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
    at Pool.promiseCallback (/home/node/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/home/node/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
    at /home/node/nodejs-pool/sql_sync/sql_sync.js:18:18
    at /home/node/nodejs-pool/node_modules/async/dist/async.js:3025:16
    at replenish (/home/node/nodejs-pool/node_modules/async/dist/async.js:882:17)
    at /home/node/nodejs-pool/node_modules/async/dist/async.js:886:9
    at eachLimit$1 (/home/node/nodejs-pool/node_modules/async/dist/async.js:3114:22)
`

**Comment by bobbieltd** [comment]
The bash will create the database for you. It seems weird error for me. You can try log in by root account to your mySQL and run 2 following command :   
GRANT ALL ON pool.* TO pool@`127.0.0.1` IDENTIFIED BY '98erhfiuehw987fh23d';
GRANT ALL ON pool.* TO pool@localhost IDENTIFIED BY '98erhfiuehw987fh23d';

**Comment by BKdilse** [comment]
Did you install MySQL yourself of let the bash script install it?  I had the same problem when I installed MySQL before running the bash script.  Ended up rebuilding Ubuntu clean.

**Comment by snoski3** [comment]
I install Ubuntu clean 16.04 LTS I let the script install MySQL with the current version but it never created the tables even if I re-run the script.  Even the "manual" way only appends the tables, it doesn't create them.
sudo mysql pool < ~/nodejs-pool/sample_config.sql

mysql> connect pool;
Connection id:    20
Current database: pool

mysql> show tables;
Empty set (0.00 sec)

mysql> exit;
Bye

**Comment by BKdilse** [comment]
weird.  I think the script you want is base.sql which creates the DB and tables.  Try running that manually, to see if it throws any errors.

**Comment by bobbieltd** [comment]
sample_config is to update values , not to create table.
Try run manually and see if there is any error with this line :  
mysql -u root --password=$ROOT_SQL_PASS < deployment/base.sql

**Comment by LetUsFsck** [comment]
+1 for this issue as well. As BKdilse and bobbieltd mention, try manual. This is what manual output looks like:
c:~/nodejs-pool$ sudo mysql -u root --password=98erhfiuehw987fh23d < deployment/base.sql
ERROR 1071 (42000) at line 139: Specified key was too long; max key length is 767 bytes

**Comment by isaack0815** [comment]
Hello,

I managed the problem.
was able to create the database by importing the base.sql. I was able to create the user via the terminal.

Now, however, I have the problem that I still use imscp for my actual website.
how can I set it now so that I come under api.domain.tld adminpanel in and can use the ui with?

do I have to do something directly at the apache settings or is it different? Can I possibly include it in the page with a require?

**Comment by snoski3** [comment]
The base.sql script worked.  I logged into mysql and ran the script.
mysql> connect pool
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Connection id:    29
Current database: pool

mysql> show tables;
+----------------+
| Tables_in_pool |
+----------------+
| balance        |
| bans           |
| block_log      |
| config         |
| payments       |
| pools          |
| port_config    |
| ports          |
| shapeshiftTxn  |
| transactions   |
| users          |
| xmrtoTxn       |
+----------------+
12 rows in set (0.00 sec)

I found the admin account in the users table but I still can't login to the web ui.
