### ISSUE TITLE
mysql Unhandled rejection Error / Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by LetUsFsck** [Snipa22/nodejs-pool#313]
During installation on Debian (and others) the following error has been found. Its usually in red text.

### _

> Unhandled rejection Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
>     at Handshake.Sequence._packetToError (/home/akumaxmr/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
>     at Handshake.ErrorPacket (/home/akumaxmr/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
>     at Protocol._parsePacket (/home/akumaxmr/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
>     at Parser.write (/home/akumaxmr/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
>     at Protocol.write (/home/akumaxmr/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
>     at Socket.<anonymous> (/home/akumaxmr/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:594:20)
> [...blahblhablhabalha]

_

It's caused by an out of date version of MariaDB due to the installer script trusting versions of "mysql-server" in aptitude repos. Anyways, you can verify this is your issue and fix it, by doing these things (tested on Debian, should work for all)

Testing if Maria's your problem today: 
1.) **mysql -V** - Check if version is below 10.2. 
-Is it? This is a problem!
2.) **sudo mysql -u root --password=98erhfiuehw987fh23d < deployment/base.sql**
-Is the output "ERROR 1071 (42000) at line 139: Specified key was too long; max key length is 767 bytes" you probably don't have a good install of MariaDB 10.2.

Fixing MariaDB:
For Debian: https://downloads.mariadb.org/mariadb/repositories/#mirror=coloserv&distro=Debian&distro_release=stretch--stretch&version=10.2
For literally all others:
https://downloads.mariadb.org/mariadb/repositories/#mirror=coloserv

NOTE: You may get an error "ERROR 1524 (HY000): Plugin 'unix_socket' is not loaded" after updating. Fix it by:
1.) **sudo editor_u_like /etc/mysql/mariadb.conf.d/50-server.cnf** and add this line:

"plugin-load-add = auth_socket.so" below [mysqld] section. 

2.) Then restart maria/sql services: 
systemctl restart mariadb.service 

3.) **sudo mysql** and then execute this command IF YOU HAVE NO DATA AND THIS IS A CLEAN INSTALL: **drop database pool;**

4.) **sudo mysql -u root --password=98erhfiuehw987fh23d < deployment/base.sql**

This should result in the base.sql getting imported properly, and thus no more tears. (Will verify and reply if any other scripts are blocked by the Maria version, but I think this is the only one.)

**Comment by swa74** [comment]
sudo mysql -u root --password = 98erhfiuehw987fh23d <deployment / base.sql ....
**98erhfiuehw987fh23d**  it's not the ROOT password ! ROOT password can be recovered in the file /root/.my.cnf
