### ISSUE TITLE
Cannot read property 'testnet' of undefined

### ISSUE THREAD

**Issue by chaturanga50** [Snipa22/nodejs-pool#33]
I'm getting below error when starting api using "pm2 restart api", & api not starting.
OS - Ubuntu

2017-02-20 08:17 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'testnet' of undefined
    at new Coin (/home/pool/nodejs-pool/lib/coins/xmr.js:31:30)
    at /home/pool/nodejs-pool/init.js:45:24
    at tryCatcher (/home/pool/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pool/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pool/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/pool/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/pool/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/pool/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/pool/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/pool/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by Snipa22** [comment]
It looks like your SQL never got inserted correctly.  The testnet variable is set in your config table.

**Comment by chaturanga50** [comment]
@Snipa22 yep, it worked after restoration. Thanks for the support.

**Comment by chaturanga50** [comment]
@Snipa22 one more thing, will you explain following little bit with examples,

Critical/Must be done:
pool/address
pool/feeAddress
general/shareHost

**Comment by Snipa22** [comment]
https://github.com/Snipa22/nodejs-pool/wiki/Configuration-Details

**Comment by chaturanga50** [comment]
Thanks
