### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by tsyuha77** [Snipa22/nodejs-pool#345]
Hello

Excuse me please, but I have installed https://github.com/Snipa22/nodejs-pool on clean vps.

My steps are:
1 - create user and add it to sudoers. Go to user mode su - etc...
2 - install all with command curl -L https://raw.githubusercontent.com/Snipa22/nodejs-pool/master/deployment/deploy.bash | bash
3 - change config.json 2 field

  "bind_ip": "0.0.0.0",
  "hostname": "real ip of my vps",
4 - change poolui/build/globals.js and poolui/build/globals.default.js

.factory('GLOBALS', function() {
        return {
                pool_name: "XMRPool.net",
                api_url : 'http://real ip of my vps/api',
                api_refresh_interval: 5000,
                app_update_interval: 5*60000
        };
});
5 -  restart api with command pm2 restart api

After this steps I try to go to http://real ip of my vps/api or http:/real ip of my vps/admin.html as in manual. And see Cannot GET / and 404 Not Found

Please help me. I do not understand what I must to do.

**Comment by BKdilse** [comment]
I've never tired IP for the hostname, so not sure if it will work.

Have you check module statuses, to see if everything is running?  using pm2 status

and then pm2 logs {module name}, to see if there are errors?

**Comment by tsyuha77** [comment]
Thank you for your answer!
It is a result of commands

pooldaemon@85:~$ pm2 status
┌──────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬────────────┬────────────┬──────────┐
│ App name     │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user       │ watching │
├──────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼────────────┼────────────┼──────────┤
│ api          │ 7  │ fork │ 21439 │ online │ 4       │ 105m   │ 0%  │ 51.1 MB    │ pooldaemon │ disabled │
│ blockManager │ 1  │ fork │ 31910 │ online │ 0       │ 21h    │ 0%  │ 345.4 MB   │ pooldaemon │ disabled │
│ longRunner   │ 5  │ fork │ 32117 │ online │ 0       │ 21h    │ 0%  │ 34.0 MB    │ pooldaemon │ disabled │
│ payments     │ 3  │ fork │ 32028 │ online │ 0       │ 21h    │ 0%  │ 25.2 MB    │ pooldaemon │ disabled │
│ pool         │ 6  │ fork │ 28823 │ online │ 119223  │ 3h     │ 0%  │ 52.4 MB    │ pooldaemon │ disabled │
│ remoteShare  │ 4  │ fork │ 32076 │ online │ 0       │ 21h    │ 0%  │ 18.7 MB    │ pooldaemon │ disabled │
│ worker       │ 2  │ fork │ 31996 │ online │ 0       │ 21h    │ 0%  │ 64.4 MB    │ pooldaemon │ disabled │
└──────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴────────────┴────────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬────────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user       │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼────────────┤
│ pm2-logrotate │ 2.4.0   │ N/A        │ online │ 0       │ 0%  │ 29.785 MB   │ pooldaemon │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴────────────┘
 Use `pm2 show <id|name>` to get more details about an app

pm2 logs show 2 types of errors - 

2|worker   | 2018-03-01 06:33 -05:00: Unable to get wallet stats: Unable to process balance
2|worker   | 2018-03-01 06:34 -05:00: Did not send e-mail successfully!  Response: undefined Response: undefined


Please help me with it

**Comment by BKdilse** [comment]
Is the wallet running?
Are there no other errors in other modules?
The pool module looks like it has a lot of restarts.

**Comment by tsyuha77** [comment]
- Is the wallet running?

I think that it's not running. I make a manual rules step by step.

- Are there no other errors in other modules?

No

- The pool module looks like it has a lot of restarts.

I have restart it by hands 5-10 times. Not more.


Thank you very much.

**Comment by tsyuha77** [comment]
I see that url http://my_ip/api/pool/stats  is working

and show this - 
{"pool_list":["pplns","solo"],"pool_statistics":{"hashRate":0,"miners":0,"totalHashes":0,"lastBlockFoundTime":0,"lastBlockFound":0,"totalBlocksFound":0,"totalMinersPaid":0,"totalPayments":0,"roundHashes":0},"last_payment":0}


As I understand something is working but no all. Please help me

**Comment by BKdilse** [comment]
looks like the api is fine.
Sorry can't think what else to check off the top of my head.

**Comment by tsyuha77** [comment]
Thank you very much!

**Comment by BKdilse** [comment]
another check, did you update file nodejs-pool/config.json?
bind_ip & hostname

**Comment by tsyuha77** [comment]
I don't understand what must I do?

**Comment by BKdilse** [comment]
Not sure if it's too import, as it should work for single node...  but section Readme - Deployment via Installer, step 3.  states the changes required.

I did have this issue, but a long time ago, and can't remember the fix.

Just double check everything you've done.  Hopefully someone on here will have some suggestions.

**Comment by tsyuha77** [comment]
My config.json ia attached - 

{
  "pool_id": 0,
  "bind_ip": "0.0.0.0",
  "hostname": "real_ip_of_my_vps",
  "db_storage_path": "/home/pooldaemon/pool_db/",
  "coin": "xmr",
  "mysql": {
    "connectionLimit": 20,
    "host": "127.0.0.1",
    "database": "pool",
    "user": "pool",
    "password": "98erhfiuehw987fh23d"
  }
}

What must I change in it?


And one question - what port must I use in programm for mining? 8000?

Please excuse me for my questions(

**Comment by BKdilse** [comment]
I know normal 0.0.0.0 works and binds to all IPs, but in this case, I don't know if it must be a real IP, you could try your actual IP, and revert back it makes no difference.

Other bits look ok.

Mining ports are 3333, 5555, 7777, 9000 as per base.sql, unless you changed them.

**Comment by tsyuha77** [comment]
Try

"bind_ip": "0.0.0.0",
"hostname": "real_ip_of_my_vps",

and 

"bind_ip": "real_ip_of_my_vps",
"hostname": "real_ip_of_my_vps",


I do not see any differencies(..

When I try to connect for mining and use port 3333 and 5555 I receive errors -


SOCKET ERROR - No active block template
SOCKET ERROR - RECEIVE Error

**Comment by BKdilse** [comment]
Not sure on that, I would trace back steps and verify every change made, is correct.

**Comment by tsyuha77** [comment]
Thank you very much. Will try domain name , bot an ip address.

**Comment by bobbieltd** [comment]
"bind_ip": "0.0.0.0",
"hostname": "real_ip_of_my_vps",

That is correct, bind_ip = 0.0.0.0, hostname : whatever you want, you can put in hostname

No active block template —> monerod is not synced. Check Monero daemon status.

**Comment by bobbieltd** [comment]
Let me guess. Just in case. I think your disk storage is smaller than 100Gb. With Monero and bash script, you need > 100 Gb (download + import XMR blockchain).

**Comment by tsyuha77** [comment]
Thank you for your answer.

monerod status is

pooldaemon@85:~$ ps ax|grep mone
  340 ?        Sl   1108:01 /usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc


my disk is

Filesystem         Size  Used Avail Use% Mounted on
/dev/ploop22518p1   64G   48G   15G  78% /

**Comment by tsyuha77** [comment]
Now try to connect and see in logs - 

/home/pooldaemon/.pm2/logs/blockManager-error-1.log last 15 lines:
1|blockMan | 2018-03-02 01:55 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 01:56 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 01:56 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 01:57 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 01:57 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 01:58 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 01:59 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 01:59 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:00 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:00 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:02 -05:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
1|blockMan | 2018-03-02 02:02 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
1|blockMan | 2018-03-02 02:04 -05:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
1|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

**Comment by BKdilse** [comment]
so blockmanager cannot connect to Monero Daemon.  Didn't you say earlier, that you had no other errors?

Try stopping Monero Daemon service, and then run the Daemon in the foreground to see what its doing:

/usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --restricted-rpc

**Comment by tsyuha77** [comment]
All my logs is  - 
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pooldaemon/.pm2/pm2.log last 15 lines:
PM2        | [2018-03-02 02:42:17] PM2 log: App [worker] with id [2] and pid [25021], exited with code [1] via signal [SIGINT]
PM2        | [2018-03-02 02:42:17] PM2 log: Starting execution sequence in -fork mode- for app name:worker id:2
PM2        | [2018-03-02 02:42:17] PM2 log: App name:worker id:2 online
PM2        | [2018-03-02 02:43:20] PM2 log: App [worker] with id [2] and pid [25368], exited with code [1] via signal [SIGINT]
PM2        | [2018-03-02 02:43:20] PM2 log: Starting execution sequence in -fork mode- for app name:worker id:2
PM2        | [2018-03-02 02:43:20] PM2 log: App name:worker id:2 online
PM2        | [2018-03-02 02:44:24] PM2 log: App [worker] with id [2] and pid [25714], exited with code [1] via signal [SIGINT]
PM2        | [2018-03-02 02:44:24] PM2 log: Starting execution sequence in -fork mode- for app name:worker id:2
PM2        | [2018-03-02 02:44:24] PM2 log: App name:worker id:2 online
PM2        | [2018-03-02 02:45:27] PM2 log: App [worker] with id [2] and pid [26061], exited with code [1] via signal [SIGINT]
PM2        | [2018-03-02 02:45:27] PM2 log: Starting execution sequence in -fork mode- for app name:worker id:2
PM2        | [2018-03-02 02:45:27] PM2 log: App name:worker id:2 online
PM2        | [2018-03-02 02:46:30] PM2 log: App [worker] with id [2] and pid [26349], exited with code [1] via signal [SIGINT]
PM2        | [2018-03-02 02:46:30] PM2 log: Starting execution sequence in -fork mode- for app name:worker id:2
PM2        | [2018-03-02 02:46:30] PM2 log: App name:worker id:2 online

/home/pooldaemon/.pm2/logs/pm2-logrotate-error-0.log last 15 lines:
/home/pooldaemon/.pm2/logs/payments-error-3.log last 15 lines:
/home/pooldaemon/.pm2/logs/remoteShare-error-4.log last 15 lines:
/home/pooldaemon/.pm2/logs/api-error-7.log last 15 lines:
/home/pooldaemon/.pm2/logs/remoteShare-out-4.log last 15 lines:
/home/pooldaemon/.pm2/logs/payments-out-3.log last 15 lines:
/home/pooldaemon/.pm2/logs/pm2-logrotate-out-0.log last 15 lines:
0|pm2-logr | "/home/pooldaemon/.pm2/logs/pm2-logrotate-out-0__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/longRunner-out-5__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/longRunner-error-5__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/api-out-7__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/blockManager-out-1__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/blockManager-error-1__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/worker-out-2__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/worker-error-2__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/pool-out-6__2018-03-02_00-00-00.log" has been created
0|pm2-logr | "/home/pooldaemon/.pm2/logs/pool-error-6__2018-03-02_00-00-00.log" has been created

/home/pooldaemon/.pm2/logs/longRunner-out-5.log last 15 lines:
5|longRunn | 2018-03-02 00:00 -05:00: Scanning from: undefined for more than: NaN shares
5|longRunn | 2018-03-02 00:59 -05:00: Cleaning up the share DB
5|longRunn | 2018-03-02 00:59 -05:00: Done cleaning up the shareDB
5|longRunn | 2018-03-02 01:00 -05:00: Scanning from: undefined for more than: NaN shares
5|longRunn | 2018-03-02 01:59 -05:00: Cleaning up the share DB
5|longRunn | 2018-03-02 01:59 -05:00: Done cleaning up the shareDB
5|longRunn | 2018-03-02 02:00 -05:00: Scanning from: undefined for more than: NaN shares

/home/pooldaemon/.pm2/logs/longRunner-error-5.log last 15 lines:
5|longRunn | 2018-03-02 00:00 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
5|longRunn | 2018-03-02 01:00 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
5|longRunn | 2018-03-02 02:00 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}

/home/pooldaemon/.pm2/logs/api-out-7.log last 15 lines:
7|api      | 2018-03-02 02:15 -05:00: Database Worker: LMDB Env Initialized.
7|api      | 2018-03-02 02:15 -05:00: Master cluster setting up 4 workers...
7|api      | 2018-03-02 02:15 -05:00: Worker 16281 is online
7|api      | 2018-03-02 02:15 -05:00: Worker 16282 is online
7|api      | 2018-03-02 02:15 -05:00: Worker 16287 is online
7|api      | 2018-03-02 02:15 -05:00: Worker 16293 is online
7|api      | 2018-03-02 02:15 -05:00: Database Worker: LMDB Env Initialized.
7|api      | 2018-03-02 02:15 -05:00: Database Worker: LMDB Env Initialized.
7|api      | 2018-03-02 02:15 -05:00: Database Worker: LMDB Env Initialized.
7|api      | 2018-03-02 02:15 -05:00: Database Worker: LMDB Env Initialized.
7|api      | 2018-03-02 02:15 -05:00: Process 16282 is listening to all incoming requests
7|api      | 2018-03-02 02:15 -05:00: Process 16281 is listening to all incoming requests
7|api      | 2018-03-02 02:15 -05:00: Process 16287 is listening to all incoming requests
7|api      | 2018-03-02 02:15 -05:00: Process 16293 is listening to all incoming requests

/home/pooldaemon/.pm2/logs/blockManager-out-1.log last 15 lines:
1|blockMan | Performing PPS payout on block: 1520677 Block Value: 5.089376658265
1|blockMan | PPS payout cycle complete on block: 1520677 Block Value: 5.089376658265 Block Payouts: 0 Payout Percentage: 0%
1|blockMan | Performing PPS payout on block: 1520678 Block Value: 5.089366951049
1|blockMan | PPS payout cycle complete on block: 1520678 Block Value: 5.089366951049 Block Payouts: 0 Payout Percentage: 0%
1|blockMan | 2018-03-02 02:37 -05:00: Performing PPS payout on block: 1520616 Block Value: 5.131957611848
1|blockMan | PPS payout cycle complete on block: 1520616 Block Value: 5.131957611848 Block Payouts: 0 Payout Percentage: 0%
1|blockMan | 2018-03-02 02:37 -05:00: Performing PPS payout on block: 1520613 Block Value: 5.103435536995
1|blockMan | 2018-03-02 02:37 -05:00: PPS payout cycle complete on block: 1520613 Block Value: 5.103435536995 Block Payouts: 0 Payout Percentage: 0%
1|blockMan | Performing PPS payout on block: 1520615 Block Value: 5.089978520212
1|blockMan | PPS payout cycle complete on block: 1520615 Block Value: 5.089978520212 Block Payouts: 0 Payout Percentage: 0%
1|blockMan | Performing PPS payout on block: 1520614 Block Value: 5.089988228594
1|blockMan | PPS payout cycle complete on block: 1520614 Block Value: 5.089988228594 Block Payouts: 0 Payout Percentage: 0%
1|blockMan | 2018-03-02 02:37 -05:00: Database Worker: LMDB Env Initialized.
1|blockMan | 2018-03-02 02:37 -05:00: Performing boot-sync
1|blockMan | 2018-03-02 02:38 -05:00: Boot-sync from SQL complete.  Pending completion of queued jobs to get back to work.

/home/pooldaemon/.pm2/logs/pool-error-6.log last 15 lines:
6|pool     | 2018-03-02 02:44 -05:00: (Worker 2 - 28851) Malformed message from 46.30.45.26 Message: quit

/home/pooldaemon/.pm2/logs/worker-out-2.log last 15 lines:
2|worker   | 2018-03-02 02:37 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:37 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:37 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:37 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:37 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:37 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:37 -05:00: Block headers identical to historical header.  Ignoring
2|worker   | 2018-03-02 02:39 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:40 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:41 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:42 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:43 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:44 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:45 -05:00: Database Worker: LMDB Env Initialized.
2|worker   | 2018-03-02 02:46 -05:00: Database Worker: LMDB Env Initialized.

/home/pooldaemon/.pm2/logs/worker-error-2.log last 15 lines:
2|worker   |     at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
2|worker   |     at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
2|worker   |     at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
2|worker   |     at emitOne (events.js:116:13)
2|worker   |     at Request.emit (events.js:211:7)
2|worker   |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
2|worker   |     at emitOne (events.js:116:13)
2|worker   |     at ClientRequest.emit (events.js:211:7)
2|worker   |     at Socket.socketErrorListener (_http_client.js:387:9)
2|worker   |     at emitOne (events.js:116:13)
2|worker   |     at Socket.emit (events.js:211:7)
2|worker   |     at emitErrorNT (internal/streams/destroy.js:64:8)
2|worker   |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2|worker   |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2|worker   | 2018-03-02 02:46 -05:00: Unable to get wallet stats: Unable to process balance

/home/pooldaemon/.pm2/logs/blockManager-error-1.log last 15 lines:
1|blockMan |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
1|blockMan | 2018-03-02 02:39 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:39 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:40 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:40 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:41 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:41 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:42 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:42 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:43 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:43 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:44 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
1|blockMan | 2018-03-02 02:46 -05:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
1|blockMan | 2018-03-02 02:46 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

/home/pooldaemon/.pm2/logs/pool-out-6.log last 15 lines:
6|pool     | 2018-03-02 02:46 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:46 -05:00: Invalid miner, disconnecting due to: No active block template
6|pool     | 2018-03-02 02:46 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:46 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:46 -05:00: Invalid miner, disconnecting due to: No active block template
6|pool     | 2018-03-02 02:46 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:46 -05:00: Processed 0/0/0/0 Trusted/Validated/Invalid/Total shares in the last 30 seconds
6|pool     | 2018-03-02 02:46 -05:00: Performing difficulty update on miners
6|pool     | 2018-03-02 02:46 -05:00: Performing difficulty update on miners
6|pool     | 2018-03-02 02:46 -05:00: Performing difficulty update on miners
6|pool     | 2018-03-02 02:46 -05:00: Performing difficulty update on miners
6|pool     | 2018-03-02 02:46 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:46 -05:00: Invalid miner, disconnecting due to: No active block template
6|pool     | 2018-03-02 02:46 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:46 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed

6|pool     | 2018-03-02 02:47 -05:00: Invalid miner, disconnecting due to: No active block template
6|pool     | 2018-03-02 02:47 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:47 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:47 -05:00: Invalid miner, disconnecting due to: No active block template
6|pool     | 2018-03-02 02:47 -05:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
6|pool     | 2018-03-02 02:47 -05:00: Processed 0/0/0/0 Trusted/Validated/Invalid/Total shares in the last 30 seconds



when I kill monerod it start without my help.

Thank you very much

**Comment by BKdilse** [comment]
Need to fix Daemon issue 1st, then re-check all logs.

Don't kill daemon.  Run:
sudo systemctl stop monero

Then run it in foreground to troubleshoot it.

**Comment by tsyuha77** [comment]
-Need to fix Daemon issue 1st

Excuse me but I don't understand what must I do?

- Then run it in foreground to troubleshoot it.
Thank you. Start daemon in console and see logs - 


pooldaemon@85:~$ /usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --restricted-rpc
2018-03-02 07:59:47.010     7f95bcbed740        INFO    global  src/daemon/main.cpp:279 Monero 'Helium Hydra' (v0.11.1.0-release)
2018-03-02 07:59:47.010     7f95bcbed740        INFO    global  src/daemon/protocol.h:55        Initializing cryptonote protocol...
2018-03-02 07:59:47.010     7f95bcbed740        INFO    global  src/daemon/protocol.h:60        Cryptonote protocol initialized OK
2018-03-02 07:59:47.010     7f95bcbed740        INFO    global  src/daemon/p2p.h:63     Initializing p2p server...
2018-03-02 07:59:51.099     7f95bcbed740        INFO    global  src/daemon/p2p.h:68     P2p server initialized OK
2018-03-02 07:59:51.099     7f95bcbed740        INFO    global  src/daemon/rpc.h:58     Initializing core rpc server...
2018-03-02 07:59:51.099     7f95bcbed740        INFO    global  contrib/epee/include/net/http_server_impl_base.h:70     Binding on 127.0.0.1:18081
2018-03-02 07:59:51.099     7f95bcbed740        INFO    global  src/daemon/rpc.h:63     Core rpc server initialized OK on port: 18081
2018-03-02 07:59:51.099     7f95bcbed740        INFO    global  src/daemon/core.h:73    Initializing core...
2018-03-02 07:59:51.099     7f95bcbed740        INFO    global  src/cryptonote_core/cryptonote_core.cpp:323     Loading blockchain from folder /home/pooldaemon/.bitmonero/lmdb ...
2018-03-02 07:59:51.297     7f95bcbed740        INFO    global  src/cryptonote_core/cryptonote_core.cpp:421     Loading checkpoints
2018-03-02 07:59:51.545     7f95bcbed740        INFO    global  src/blockchain_db/lmdb/db_lmdb.cpp:578  [batch] DB resize needed
2018-03-02 07:59:51.546     7f95bcbed740        INFO    global  src/blockchain_db/lmdb/db_lmdb.cpp:494  LMDB Mapsize increased.  Old: 2660MiB, New: 3684MiB
2018-03-02 07:59:51.546     7f95bcbed740        INFO    global  src/daemon/core.h:78    Core initialized OK
2018-03-02 07:59:51.546     7f95bcbed740        INFO    global  src/daemon/rpc.h:68     Starting core rpc server...
2018-03-02 07:59:51.546 [SRV_MAIN]      INFO    global  src/daemon/rpc.h:73     Core rpc server started ok
2018-03-02 07:59:51.546 [SRV_MAIN]      INFO    global  src/daemon/p2p.h:78     Starting p2p net loop...
2018-03-02 07:59:52.547 [P2P1]  INFO    global  src/cryptonote_core/cryptonote_core.cpp:1258
**********************************************************************
The daemon will start synchronizing with the network. This may take a long time to complete.

You can set the level of process detailization* through "set_log <level|categories>" command*,
where <level> is between 0 (no details) and 4 (very verbose), or custom category based levels (eg, *:WARNING)

Use the "help" command to see the list of available commands.
**********************************************************************

2018-03-02 07:59:52.547 [P2P1]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1282    **********************************************************************
2018-03-02 07:59:52.547 [P2P1]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1283    Last scheduled hard fork time shows a daemon update is needed now.
2018-03-02 07:59:52.547 [P2P1]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1284    **********************************************************************
2018-03-02 07:59:53.173 [P2P1]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:305     [31.128.159.34:18080 OUT] Sync data returned a new top block candidate: 136970 -> 1520724 [Your node is 1383754 blocks (1315 days) behind]
SYNCHRONIZATION started
2018-03-02 07:59:54.232 [P2P5]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1154    [31.128.159.34:18080 OUT]  Synced 137070/1520724
2018-03-02 07:59:55.454 [P2P5]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1154    [31.128.159.34:18080 OUT]  Synced 137170/1520724

**Comment by BKdilse** [comment]
ok, so now Daemon is running, and synching.  It will take some time, maybe 1-2 days depending on speed of network.  Keep an eye on it.  Once it has fully synch'd, you should be able to re-start the modules using:

pm2 restart all

Then check the logs again for errors.

This is only a temporary workaround.  You need to check the "monero" service, to see why it is not working.  Or you can just leave it like this for now, or maybe run it in a screen session.

**Comment by tsyuha77** [comment]
I can give you an access to my server.

**Comment by BKdilse** [comment]
For now, let the daemon sync, so it gets close to readiness.  I can have a quick look later today.  You can send details to support@gntl.co.uk.

**Comment by BKdilse** [comment]
Your disk will not be big enough btw, I would personally trash this, and rebuild using a 100GB+ disk.
I am running my pool on 150GB disk, because my 100GB was not big enough, and came close to running out.  I host my pool on my own server, so I expanded the disk using gparted.

Not sure what options you have on your VPS for disk expansion, but you will have to play around with Ubuntu sizing as well.

Probably easier to rebuild at this stage, as its not live and hashing.

**Comment by tsyuha77** [comment]
Ok, thank you. I will rebuild my disk.

**Comment by tsyuha77** [comment]
I have reinstall all on vps with 120 Gb disk space. I do not see any differencies.( My client doesn't connect to pool.

Please help.

**Comment by RHood78** [comment]
I am having some issues getting this going also and noticed that the deploy.bash script has the old version 0.11.1.0  of monero. We are now on 0.13.0.4... I have removed the old monerod (v.0.11.1.0), installed the latest version and now started to sync to the blockchain with monerod (0.13.0.4). I will be sure to update if this fixes my issues.
