### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tsyuha77** [Snipa22/nodejs-pool#355]
Hello.

Yesterday I have installed nodejs-pool. Today in pm2 log I see errors

/home/pooldaemon/.pm2/logs/longRunner-error-6.log last 15 lines:
6|longRunn | 2018-03-08 00:48 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
6|longRunn | 2018-03-08 01:48 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
6|longRunn | 2018-03-08 02:48 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}

/home/pooldaemon/.pm2/logs/blockManager-error-2.log last 15 lines:
2|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:37 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:38 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:39 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:39 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:40 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:41 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:42 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:42 -05:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | 2018-03-08 03:43 -05:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}
2|blockMan | Upstream error from the block daemon.  Resetting scanner due to: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":18081}

/home/pooldaemon/.pm2/logs/worker-error-3.log last 15 lines:
3|worker   |     at /home/pooldaemon/nodejs-pool/lib/support.js:100:24
3|worker   |     at Object.parseBody (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:74:12)
3|worker   |     at Request._callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/main.js:148:26)
3|worker   |     at self.callback (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
3|worker   |     at emitOne (events.js:116:13)
3|worker   |     at Request.emit (events.js:211:7)
3|worker   |     at Request.onRequestError (/home/pooldaemon/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
3|worker   |     at emitOne (events.js:116:13)
3|worker   |     at ClientRequest.emit (events.js:211:7)
3|worker   |     at Socket.socketErrorListener (_http_client.js:387:9)
3|worker   |     at emitOne (events.js:116:13)
3|worker   |     at Socket.emit (events.js:211:7)
3|worker   |     at emitErrorNT (internal/streams/destroy.js:64:8)
3|worker   |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
3|worker   |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

What must I do? Please help me

**Comment by bobbieltd** [comment]
Ubuntu 16.04 + disk storage > 100 Gb.

**Comment by tsyuha77** [comment]
I already have ubuntu 16.04 and disk space 120 GB.

**Comment by bobbieltd** [comment]
Type this command : sudo systemctl status monero

And give me the output.

**Comment by tsyuha77** [comment]
pooldaemon@ts:~$ sudo systemctl status monero
● monero.service - Monero Daemon
   Loaded: loaded (/lib/systemd/system/monero.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-03-07 05:33:03 EST; 1 day 1h ago
  Process: 276 ExecStart=/usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/monero.service
           └─337 /usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc

Mar 07 05:33:03 ts.tm.ua systemd[1]: Starting Monero Daemon...
Mar 07 05:33:03 ts.tm.ua monerod[276]: 2018-03-07 10:33:03.532            7fc87b5c6740        INFO         global        src/daemon/main.cpp:279        Moner
Mar 07 05:33:03 ts.tm.ua monerod[276]: Forking to background...
Mar 07 05:33:03 ts.tm.ua systemd[1]: Started Monero Daemon.

**Comment by bobbieltd** [comment]
Thanks.
Your Monero daemon runs well but somehow the pool can not connect to it.
Try with any Monero wallet to see if you can access or see the balance.
1. Type : /usr/local/src/monero/build/release/bin/monero-wallet-cli
2. Create whatever wallet (or restore from your own seeds/keys)
3. At wallet > , type status

Give me the output.

**Comment by tsyuha77** [comment]
I try command from 1.

pooldaemon@ts:~$ /usr/local/src/monero/build/release/bin/monero-wallet-cli
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to /usr/local/src/monero/build/release/bin/monero-wallet-cli.log
Specify wallet file name (e.g., MyWallet). If the wallet doesn't exist, it will be created.
Wallet file name (or Ctrl-C to quit): ts
No wallet found with that name. Confirm creation of new wallet named: ts
(Y/Yes/N/No): Y
Generating new wallet...
Enter new wallet password: ******
Confirm Password: ******
List of available languages for your wallet's seed:
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
Enter the number corresponding to the language of your choice: 7

Generated new wallet: 4AavtiuZzvfGzyPxHQkreqRzs5K9kQWYy3buwvZ61hCQ5kSEX8KUEWkiViQXeTYVLH1QTAN5j2jrdSGvgtffS1Qu5MtbGza
View key: e9183e423803d7f7ffe52af5afe31b9f6424cec7743daa611c04b8b9970dfd05
**********************************************************************
Your wallet has been generated!
To start synchronizing with the daemon, use "refresh" command.
Use "help" command to see the list of available commands.
Always use "exit" command when closing monero-wallet-cli to save your
current session's state. Otherwise, you might need to synchronize
your wallet again (your wallet keys are NOT at risk in any case).


PLEASE NOTE: the following 25 words can be used to recover access to your wallet. Please write them down and store them somewhere safe and secure. Please do not store them in your email or on file storage services outside of your immediate control.

русский сцена бадья отъезд пациент китаец ладонь сынок
флаг верить женщина лагерь хищник улица нрав средство
очаг дрожать эмблема ласковый взвод кисть чайник штора очаг
**********************************************************************
Error: wallet failed to connect to daemon: http://localhost:18081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Error: wallet failed to connect to daemon: http://localhost:18081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Background refresh thread started


Please help. Thank you

**Comment by bobbieltd** [comment]
Type : sudo systemctl restart monero
Give me the output

**Comment by bobbieltd** [comment]
One more command : tail -f /home/monerodaemon/.bitmonero/bitmonero.log
Give me last 10 lines of that daemon log file

**Comment by tsyuha77** [comment]
tail -f /home/monerodaemon/.bitmonero/bitmonero.log


2018-03-08 11:39:16.694 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:159      [17] /usr/local/src/monero/build/release/bin/monerod:boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::asio::detail::is_continuation_if_running> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x234 [0x604c84]
2018-03-08 11:39:16.695 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:159      [18] /usr/local/src/monero/build/release/bin/monerod:boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x15c [0x57df3c]
2018-03-08 11:39:16.695 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:159      [19] /usr/local/src/monero/build/release/bin/monerod:epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::worker_thread()+0x807 [0x59e7a7]
2018-03-08 11:39:16.695 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:159      [20] /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0+0x115d5 [0x7fc879ae45d5]
2018-03-08 11:39:16.695 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:159      [21] /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7fc878ee16ba]
2018-03-08 11:39:16.695 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:159      [22] /lib/x86_64-linux-gnu/libc.so.6:clone+0x6d [0x7fc878c1741d]
2018-03-08 11:39:16.695 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:159
2018-03-08 12:33:22.093 [P2P4]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1282    **********************************************************************
2018-03-08 12:33:22.093 [P2P4]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1283    Last scheduled hard fork time shows a daemon update is needed now.
2018-03-08 12:33:22.093 [P2P4]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1284    **********************************************************************
2018-03-08 13:01:36.251 [P2P5]  INFO    global  src/cryptonote_core/blockchain.cpp:1427 ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 1525249
id:     <1bb55b613a421e6107a0b139500ffc24d7cd85db1dae612c3acb0a94eb375d13>
PoW:    <e2aa30109b61cde5180b22ad2f11680b1ecd8143307145c043ffdb0400000000>
difficulty:     124943042612
2018-03-08 13:01:36.267 [P2P5]  INFO    global  src/cryptonote_core/blockchain.cpp:1416 ###### REORGANIZE on height: 1525249 of 1525249 with cum_difficulty 10726480271057483
 alternative blockchain size: 2 with cum_difficulty 10726605144323300
2018-03-08 13:01:36.478 [P2P5]  INFO    global  src/cryptonote_core/blockchain.cpp:1427 ----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 1525249
id:     <538bbc9ece6233e68c7b42fcb7aa76a3eccb8b614d91b786fe795e4876d3a308>
PoW:    <65d4051e1bf04ff2535570058f07ec47042d85ec7276ef0f6c70630700000000>
difficulty:     124943042612
2018-03-08 13:01:36.478 [P2P5]  WARN    blockchain.db.lmdb      src/blockchain_db/lmdb/db_lmdb.cpp:2674 WARNING: batch transaction mode already enabled, but asked to enable batch mode
2018-03-08 13:01:36.502 [P2P5]  INFO    global  src/cryptonote_core/blockchain.cpp:892  REORGANIZE SUCCESS! on height: 1525249, new blockchain size: 1525251
2018-03-08 13:01:36.505 [P2P5]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1154    [136.243.46.107:34084 INC]  Synced 1525251/1525251
2018-03-08 13:01:36.505 [P2P5]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1521    SYNCHRONIZED OK
2018-03-08 13:01:36.544 [P2P6]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1521    SYNCHRONIZED OK
2018-03-08 13:01:36.707 [P2P6]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1521    SYNCHRONIZED OK
2018-03-08 13:01:37.853 [P2P1]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1521    SYNCHRONIZED OK
2018-03-08 13:01:52.745 [P2P7]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1521    SYNCHRONIZED OK

**Comment by bobbieltd** [comment]
Expected behaviour :
Wallet and pool can connect and communicate with monero daemon.

Actual behaviour :
Monero daemon run well and is fully synced but nothing can connect.

Cause :
Sorry, I stuck here and I don’t know.

Solution :
Reinstall everything from scratch, empty new Ubuntu 16.04.

**Comment by bobbieltd** [comment]
You can rent a VPS at Amazon with 4Gb RAM and 100 Gb disk. Reinstallation to learn. Amazone cost is high, just to be easy to learn at first. After you know everything, you can go to another cheap providers.

**Comment by tsyuha77** [comment]
I already reinstall all on clean ubuntu 5 times. Every time I see the same.

My hoster is Hetzner

**Comment by BKdilse** [comment]
Something is failing to install (I believe).

What I will suggest is what I did when I was building my 1st ever pool, and could find what the issue was.  I also re-built the server several times.

**Try this:**
Download deploy.bash onto your PC, and run a few steps at a time, using copy and past into your SSH Client.  this way, if something has gone wrong but continued in the script, you will see it.

It will install perfectly fine using this method, as I now do this for every pool install.  Obviously refer to the latest deply.bash on the repo you are using.

**Comment by bobbieltd** [comment]
I already narrowed the issue for you. In fact, it has nothing about the pool, it’s not pool issue. It’s monero issue. You don’t need to test pool. You need to find out if you can use the Monero wallet.

**Comment by bobbieltd** [comment]
The question here is not “Why doesn’t my pool work ?”. I rephrase for you your question “Why does’t my Monero work ?”. Even the wallet cli, it doesn’t work.

**Comment by bobbieltd** [comment]
For Monero, I lost 50 times of repeated reinstallation. For 5 times, it’s nothing to compare with me at the beginning.
If I count to today, it’s more 100 times that I install pools. It’s not one time and successful.

**Comment by BKdilse** [comment]
Could it be an issue with latest source?  I see some changes made

**Comment by BKdilse** [comment]
@tsyuha77 maybe try deleting the monero directory, and run the re-download, and compile, whilst monitoring for any errors.

**Comment by tsyuha77** [comment]
- @tsyuha77 maybe try deleting the monero directory, and run the re-download, and compile, whilst monitoring for any errors.

Please understand where is the monero directory? And what must I run and re-download and complie?

**Comment by bobbieltd** [comment]
You can’t all your stuffs here. You need to learn by yourself at first. Ask Google. If you can’t still find your Google answer, you can ask here.
Try to learn to compile and use Monero wallet to have better knowledge here https://github.com/monero-project/monero
You can’t run a pool if you don’t know how to use wallet (Pool need two wallets to run).
