### ISSUE TITLE
API consuming 100% of CPU, pool crashing

### ISSUE THREAD

**Issue by shigutso** [Snipa22/nodejs-pool#382]
This has been happening since yesterday, out of nowhere the CPU usage of my pool goes to 100% when the API is up. If the other modules are working, the pool works fine.

I also noticed that MYSQL is using lots of CPU, with that error showing up multiple times in `/var/log/mysql/error.log`

`2018-04-05T19:34:36.349922Z 966 [Note] Aborted connection 966 to db: 'pool' user: 'pool' host: 'localhost' (Got an error reading communication packets)`

Increased `max_allowed_packet` from the default's 16M to 256M, which seemed to fix the issue, but it's happening again.

This shows up in pm2 logs when the API crashes (due to CPU usage):

```
2018-04-05 19:24 +00:00: Unhandled rejection Error: ER_CON_COUNT_ERROR: Too many connections
    at Handshake.Sequence._packetToError (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.Sequence.end (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.ErrorPacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Handshake.js:132:8)
    at Protocol._parsePacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

Any ideas of what might be happening?
`mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper`
`pm2 2.9.1`

Thanks

**Comment by Snipa22** [comment]
Increase your MySQL connection count limits.

**Comment by vitorgatti** [comment]
![image](https://user-images.githubusercontent.com/5687102/38392114-b3657bc4-38fc-11e8-9bf4-c8bb55797a30.png)

MYSQL is using too much CPU...

**Comment by vitorgatti** [comment]
same issue happened even with max_connections set to 400 :(

`2018-04-05T21:29:59.889264Z 23 [Note] Aborted connection 23 to db: 'pool' user: 'pool' host: 'localhost' (Got an error reading communication packets)`

**Comment by Snipa22** [comment]
I usually set 2-3k on most of my machines.

**Comment by BKdilse** [comment]
@Snipa22 would the change be a good recommendation as standard, or only if issues are encountered?

**Comment by vitorgatti** [comment]
MySQL is being flooded by this query (from API I guess):

```
2018-04-06T12:59:17.043755Z       251 Query     SELECT pool_type FROM payments WHERE transaction_id = 488 LIMIT 1
2018-04-06T12:59:17.044075Z       296 Query     SELECT pool_type FROM payments WHERE transaction_id = 308 LIMIT 1
2018-04-06T12:59:17.044078Z       298 Query     SELECT pool_type FROM payments WHERE transaction_id = 307 LIMIT 1
```
~6000 queries per second of the same query as above

Is there any way to limit the calls received by a client in the API?

Thanks

**Comment by vitorgatti** [comment]
I'll try that, thanks @bobbieltd

**Comment by knoxcard** [comment]
Wowzers, 5k pool.  I know there is fail2ban https://github.com/fail2ban/fail2ban/releases for firewall, you can ban IP's that hit the system too much.  I know how to do this in nodejs and will be contributing to this project soon.

Is there an index set for the transaction_id in the mysql db? just checking...

**Comment by shigutso** [comment]
It seems that it was something on my poolui that I customized that was destroying the mysql instance. Reverted some stuff and the server is working fine again.

Thanks everyone
