### ISSUE TITLE
Sumocoin Support

### ISSUE THREAD

**Issue by CoFix** [Snipa22/nodejs-pool#395]
Hello Dev Team,

Can you reconfigure sumocoins files for new fork?
https://github.com/ArqTras/nodejs-pool/blob/master/lib/coins/sumo.js
https://github.com/ArqTras/nodejs-pool/blob/master/lib/payment_systems/sumo.js

Thank You.

**Comment by falcron11468** [comment]
Hi @CoFix 
I don't require any payment, partly because I find learning about this fun and interesting, and partly because I am garbage at this.  I can suggest going through and comparing 2 coin's files side by side and look for the differences.  Then double check those differences to make sure they are correct for your needs.  For instance - Take sumo.js and compare with aeon.js and look to see what is different.  Then hunt down the answers and find why they are different.  Also, Check to make sure your brackets are correct.  I legit spent about 2 days searching for an error, and had to get help.  Thankfully a community member helped.

I wish I could be of more help, but that's all I got.  Also, if you figure it out, you can better administer your pool, and keep it reliable.  

One more thing: `https://github.com/Snipa22/nodejs-pool/pull/353` I can see you go this from ArqTras.  From what I can tell from his response at the bottom of the aforementioned link, is that his code is either ready, not ready, and/or made for his specific fork.  

Good Luck

**Comment by CoFix** [comment]
@falcron11468 

I tried install Masari from your repo. But when i run pool, i am getting this error. This error is about installing problem? Or it doesnt work?

/home/msr/.pm2/logs/pool-out-7.log last 15 lines:
/home/msr/.pm2/logs/pool-error-7.log last 15 lines:
7|pool | at processImmediate [as _immediateCallback] (timers.js:722:5)
7|pool | 2018-04-12 08:08 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
7|pool | TypeError: Cannot read property 'funcFile' of undefined
7|pool | at /home/msr/nodejs-pool/init.js:46:42
7|pool | at tryCatcher (/home/msr/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
7|pool | at Promise._settlePromiseFromHandler (/home/msr/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
7|pool | at Promise._settlePromise (/home/msr/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
7|pool | at Promise._settlePromise0 (/home/msr/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
7|pool | at Promise._settlePromises (/home/msr/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
7|pool | at Async._drainQueue (/home/msr/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
7|pool | at Async._drainQueues (/home/msr/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
7|pool | at Immediate.Async.drainQueues (/home/msr/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
7|pool | at runCallback (timers.js:789:20)
7|pool | at tryOnImmediate (timers.js:751:5)
7|pool | at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by falcron11468** [comment]
well it sounds like you got the site up, its just the pool giving issue.  Can you give me more than the last 15 lines?  I think its the payments, which i am still having trouble on.
