### ISSUE TITLE
ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'

### ISSUE THREAD

**Issue by novaws** [Snipa22/nodejs-pool#398]
I see these errors when I try to delete something in the admin panel.
I think the problem is in some kind of modules nodejs?
How can I fix this?

```
1|api      | 2018-04-18 08:28 +00:00: Unhandled rejection Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
1|api      |     at Query.Sequence._packetToError (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
1|api      |     at Query.ErrorPacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
1|api      |     at Protocol._parsePacket (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
1|api      |     at Parser.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
1|api      |     at Protocol.write (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
1|api      |     at Socket.<anonymous> (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
1|api      |     at emitOne (events.js:116:13)
1|api      |     at Socket.emit (events.js:211:7)
1|api      |     at addChunk (_stream_readable.js:263:12)
1|api      |     at readableAddChunk (_stream_readable.js:250:11)
1|api      |     at Socket.Readable.push (_stream_readable.js:208:10)
1|api      |     at TCP.onread (net.js:594:20)
1|api      |     --------------------
1|api      |     at Pool.query (/home/pooldaemon/nodejs-pool/node_modules/mysql/lib/Pool.js:199:23)
1|api      |     at /home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
1|api      |     at Promise._execute (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
1|api      |     at Promise._resolveFromExecutor (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
1|api      |     at new Promise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
1|api      |     at Pool.promiseCallback (/home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
1|api      |     at pool.query (/home/pooldaemon/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
1|api      |     at /home/pooldaemon/nodejs-pool/lib/api.js:703:18
1|api      |     at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
1|api      |     at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:131:13)
1|api      |     at Route.dispatch (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/route.js:112:3)
1|api      |     at Layer.handle [as handle_request] (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
1|api      |     at /home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:277:22
1|api      |     at Function.process_params (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:330:12)
1|api      |     at next (/home/pooldaemon/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
1|api      |     at /home/pooldaemon/nodejs-pool/lib/api.js:564:17
```

**Comment by novaws** [comment]
Ubuntu 16.04
mysql  5.7.21
---
all data persist in tables;

``
mysql> select * from port_config;
+----------+------------+---------------------------------------+----------+--------+------+
| poolPort | difficulty | portDesc                              | portType | hidden | ssl  |
+----------+------------+---------------------------------------+----------+--------+------+
|     3333 |       1000 | Low-End Hardware (Up to 30-40 h/s)    | pplns    |      0 |    0 |
|     5555 |       5000 | Medium-Range Hardware (Up to 160 h/s) | pplns    |      0 |    0 |
|     7777 |      10000 | High-End Hardware (Anything else!)    | pplns    |      0 |    0 |
|     9000 |      20000 | Claymore SSL                          | pplns    |      0 |    1 |
+----------+------------+---------------------------------------+----------+--------+------+
4 rows in set (0.00 sec)

mysql>
``

**Comment by novaws** [comment]
if i update pool dif manual, this change does not appy, after restart difficulty  back to 1000 example...
