### ISSUE TITLE
TypeError: Cannot read property 'blocktemplate_blob' of undefined

### ISSUE THREAD

**Issue by chaturanga50** [Snipa22/nodejs-pool#40]
Getting error in pool error log.
OS - Ubuntu

`2017-02-22 03:51 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
2017-02-22 03:51 +00:00: TypeError: Cannot read property 'blocktemplate_blob' of undefined
    at /home/pool/nodejs-pool/lib/pool.js:141:48
    at /home/pool/nodejs-pool/lib/coins/xmr.js:72:20
    at /home/pool/nodejs-pool/lib/support.js:103:20
    at Object.parseBody (/home/pool/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pool/nodejs-pool/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/home/pool/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pool/nodejs-pool/node_modules/request-json/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pool/nodejs-pool/node_modules/request-json/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)`

**Comment by Snipa22** [comment]
This is your pool having issues connecting to the monero daemon.  Check your daemon connections and/or ensuring that your monero daemon is running properly.  Monero is prepping to release a new tag today, so I'll be migrating my test servers today for stability testing.

**Comment by chaturanga50** [comment]
@Snipa22 monero daemon is running properly and able to telnet without any issue.

**Comment by Snipa22** [comment]
Is this still happening after the 0.10.2.1 daemon upgrade?  Everything appears to be much more stable after that.

**Comment by chaturanga50** [comment]
@Snipa22 yes, upgraded 0.10.2.1 and still getting error and pools ports are not starting up.

**Comment by chaturanga50** [comment]
@Snipa22 also in pool-out.log showing as below repeatedly,

`2017-02-26 11:49 +00:00: Worker 32627 is online
2017-02-26 11:49 +00:00: Database Worker: LMDB Env Initialized.
2017-02-26 11:49 +00:00: Database Worker: LMDB Env Initialized.
2017-02-26 11:49 +00:00: Worker 32575 died with code: 1, and signal: null
Starting a new worker
2017-02-26 11:49 +00:00: Worker 316 is online
2017-02-26 11:49 +00:00: Worker 32627 died with code: 1, and signal: null
Starting a new worker
2017-02-26 11:49 +00:00: Worker 329 is online
2017-02-26 11:49 +00:00: Database Worker: LMDB Env Initialized.
2017-02-26 11:49 +00:00: Database Worker: LMDB Env Initialized.
2017-02-26 11:49 +00:00: Worker 316 died with code: 1, and signal: null
Starting a new worker
2017-02-26 11:49 +00:00: Worker 329 died with code: 1, and signal: null
Starting a new worker
2017-02-26 11:49 +00:00: Worker 485 is online
2017-02-26 11:49 +00:00: Worker 497 is online`

**Comment by Snipa22** [comment]
That can't be in pool-out.log, the pool is unable to initialize LMDB, as it doesn't have access.  Worker is crashing, you've probably got a broken configuration somewhere.  Did you finish configuration as outlined in the readme?

**Comment by chaturanga50** [comment]
@Snipa22 yes, completed those, 

pool/address - 127.0.0.1
pool/feeAddress - Generated new wallet key in payout/feeAddress
general/shareHost - 127.0.0.1

**Comment by Snipa22** [comment]
Have you updated to the v0.10.2.1 Monero release?  This fixes a number of BT bugs.

**Comment by chaturanga50** [comment]
@Snipa22 yes

**Comment by Snipa22** [comment]
Please hop on IRC in that case, and we can try to help you more there.  This is not an ideal forum for assisting you.  This is a local bug in your deployment, and not a bug in the software at this point, as I've deployed two more pools in testing, and they test clean.

**Comment by daveinli** [comment]
Hi Snipa22, want to deploy a 3rd. Chaturanga50 is trying but we are faced with the same error over and over. I can give you access to the front and back if you want to try and deploy this for us.
