### ISSUE TITLE
cryptonote-util fails to compile

### ISSUE THREAD

**Issue by Ossii** [Snipa22/nodejs-pool#409]
System is Ubuntu 18.04 LTS server
The weird thing is if I use https://github.com/svirusxxx/node-cryptonote-util#xmr-Nan-2.0, it compiles fine.
But its to me an unknown repo, so I rather find the fix here..

Thanks.

```
> cryptonote-util@0.0.3 install /home/testpool/nodejs-pool/node_modules/cryptonote-util
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/testpool/nodejs-pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function 'bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)':
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function 'std::size_t crypto::rs_comm_size(std::size_t)':
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type 'crypto::rs_comm::<unnamed struct> []'
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:115: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/testpool/nodejs-pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/testpool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/home/testpool/.nvm/versions/node/v8.9.3/bin/node" "/home/testpool/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/testpool/nodejs-pool/node_modules/cryptonote-util
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/testpool/.npm/_logs/2018-05-09T05_01_02_954Z-debug.log
```

**Comment by bobbieltd** [comment]
Try "cryptoforknote-util": "git+https://github.com/MoneroOcean/node-cryptoforknote-util.git#v1.0.0"
In coin javascript, change node-cryptonode-util to cryptoforknote-util

**Comment by Ossii** [comment]
That compiles fine indeed, another known developer so then I'll take that as good stuff ;)

**Comment by Ossii** [comment]
Extra note, lib/api.js also needs to be updated to use cryptoforknote-util.
