### ISSUE TITLE
blockManger alltime restart

### ISSUE THREAD

**Issue by Weiss1985** [Snipa22/nodejs-pool#444]
<--- JS stacktrace --->
3|blockMan | ==== JS stack trace =========================================
3|blockMan | Security context: 0x3d0899ea5ee1 <JSObject>
3|blockMan |     1: /* anonymous */(aka /* anonymous */) [/home/weiss/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:~113] [pc=0x3d61acc3e8cc](this=0x25f7ef702311 <undefined>)
3|blockMan |     2: arguments adaptor frame: 1->0
3|blockMan |     3: /* anonymous */(aka /* anonymous */) [/home/weiss/nodejs-pool/lib/blockManager.js:~468] [pc=0x3d61acc49eeb](this=0x25f7ef702311 <undefined>,blockID=...
3|blockMan | 2018-07-24 02:04 +00:00: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
3|blockMan |  1:
3|blockMan | 2018-07-24 02:04 +00:00: node::Abort() [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  2:
3|blockMan | 2018-07-24 02:04 +00:00: 0x121a7ac [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  3:
3|blockMan | 2018-07-24 02:04 +00:00: v8::Utils::ReportOOMFailure(char const*, bool) [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  4:
3|blockMan | 2018-07-24 02:04 +00:00: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  5:
3|blockMan | 2018-07-24 02:04 +00:00: v8::internal::Handle<v8::internal::JSFunction> v8::internal::Factory::New<v8::internal::JSFunction>(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationSpace) [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  6:
3|blockMan | 2018-07-24 02:04 +00:00: v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::PretenureFlag) [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  7:
3|blockMan | 2018-07-24 02:04 +00:00: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Cell>, v8::internal::PretenureFlag) [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  8:
3|blockMan | 2018-07-24 02:04 +00:00: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::Handle<v8::internal::Cell>, v8::internal::PretenureFlag) [node /home/weiss/nodejs-pool/init.js]
3|blockMan |  9:
3|blockMan | 2018-07-24 02:04 +00:00: v8::internal::Runtime_NewClosure_Tenured(int, v8::internal::Object**, v8::internal::Isolate*) [node /home/weiss/nodejs-pool/init.js]
3|blockMan | 10:
3|blockMan | 2018-07-24 02:04 +00:00: 0x3d61acb0463d
3|blockMan | 2018-07-24 02:04 +00:00: Database Worker: LMDB Env Initialized.
3|blockMan | 2018-07-24 02:04 +00:00: Performing boot-sync
3|blockMan | 2018-07-24 02:04 +00:00: Boot-sync from SQL complete.  Pending completion of queued jobs to get back to work.

HDD - 500GB
RAM 8gb

Help please

**Comment by bobbieltd** [comment]
8Gb RAM is more than enough. Out of memomry can be caused by coin daemon memory leak (it happens with some forknote coins).

**Comment by Weiss1985** [comment]
Monero coin.
Daemon from - https://getmonero.org/resources/user-guides/vps_run_node.html

**Comment by bobbieltd** [comment]
Monero doesn’t have any memory issue as I know. 🤔
What “free -h” gives you about memory ? Is monerod fully synced ? (By tail the bitmonero.log)

**Comment by Weiss1985** [comment]
free -h
              total        used        free      shared  buff/cache   available
Mem:           7.7G        2.4G        1.9G        9.6M        3.3G        4.9G
Swap:          4.9G         33M        4.8G

Yes fully synced....

**Comment by Weiss1985** [comment]
Help please..

**Comment by bobbieltd** [comment]
I can’t figure out why your blockManager have issue of memory allocation (with 4.9Gb RAM available).
Do you have any other error logs ?

**Comment by bobbieltd** [comment]
Output for “pm2 status” ?

**Comment by Weiss1985** [comment]
pm2 status 
Only blockManger constantly reboots...
With errors in the first post.

**Comment by Weiss1985** [comment]
==== JS stack trace =========================================
2|blockMan | Security context: 0xa7ae5425ee1 <JSObject>
2|blockMan |     1: /* anonymous */(aka /* anonymous */) [/home/weiss/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:~113] [pc=0x116c468cd52c](this=0x1e7314202311 <undefined>)
2|blockMan |     2: arguments adaptor frame: 1->0
2|blockMan |     3: /* anonymous */(aka /* anonymous */) [/home/weiss/nodejs-pool/lib/blockManager.js:~468] [pc=0x116c468cbfeb](this=0x1e7314202311 <undefined>,blockID=1...
2|blockMan | 2018-07-26 23:17 +00:00: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2|blockMan |  1:
2|blockMan | 2018-07-26 23:17 +00:00: node::Abort() [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  2:
2|blockMan | 2018-07-26 23:17 +00:00: 0x121a7ac [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  3: v8::Utils::ReportOOMFailure(char const*, bool) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  4:
2|blockMan | 2018-07-26 23:17 +00:00: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  5:
2|blockMan | 2018-07-26 23:17 +00:00: v8::internal::Handle<v8::internal::JSFunction> v8::internal::Factory::New<v8::internal::JSFunction>(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationSpace) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  6:
2|blockMan | 2018-07-26 23:17 +00:00: v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::PretenureFlag) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  7:
2|blockMan | 2018-07-26 23:17 +00:00: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Cell>, v8::internal::PretenureFlag) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  8:
2|blockMan | 2018-07-26 23:17 +00:00: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::Handle<v8::internal::Cell>, v8::internal::PretenureFlag) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  9:
2|blockMan | 2018-07-26 23:17 +00:00: v8::internal::Runtime_NewClosure_Tenured(int, v8::internal::Object**, v8::internal::Isolate*) [node /home/weiss/nodejs-pool/init.js]
2|blockMan | 10: 0x116c4678463d
2|blockMan | 2018-07-26 23:17 +00:00: Database Worker: LMDB Env Initialized.
2|blockMan | 2018-07-26 23:17 +00:00: Performing boot-sync
2|blockMan | 2018-07-26 23:17 +00:00: Boot-sync from SQL complete.  Pending completion of queued jobs to get back to work.
2|blockMan | 2018-07-26 23:18 +00:00:
2|blockMan | <--- Last few GCs --->
2|blockMan | [11901:0x33aba70]    59452 ms: Mark-sweep 1402.5 (1451.2) -> 1402.5 (1441.2) MB, 2948.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2949 ms) last resort GC in old space requested
2|blockMan | [11901:0x33aba70]    62521 ms: Mark-sweep 1402.5 (1441.2) -> 1402.5 (1441.2) MB, 3069.2 / 0.0 ms  last resort GC in old space requested
2|blockMan | <--- JS stacktrace --->
2|blockMan | ==== JS stack trace =========================================
2|blockMan | Security context: 0xe0ec8b25ee1 <JSObject>
2|blockMan |     1: /* anonymous */(aka /* anonymous */) [/home/weiss/nodejs-pool/lib/blockManager.js:~468] [pc=0x4ec90fc5a19](this=0x3509b1402311 <undefined>,blockID=1411359)
2|blockMan |     2: arguments adaptor frame: 3->1
2|blockMan |     3: forEach(this=0x2551ebb84089 <JSArray[1625354]>)
2|blockMan |     5: /* anonymous */(aka /* anonymous */) [/home/weiss/nodejs-pool/lib/blockManager.js:468] [bytecode=0xbdfbb79c561 offset=179](this=0x3509b14...
2|blockMan | 2018-07-26 23:18 +00:00: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2|blockMan |  1:
2|blockMan | 2018-07-26 23:18 +00:00: node::Abort() [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  2: 0x121a7ac [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  3:
2|blockMan | 2018-07-26 23:18 +00:00: v8::Utils::ReportOOMFailure(char const*, bool) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  4:
2|blockMan | 2018-07-26 23:18 +00:00: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  5:
2|blockMan | 2018-07-26 23:18 +00:00: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  6:
2|blockMan | 2018-07-26 23:18 +00:00: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node /home/weiss/nodejs-pool/init.js]
2|blockMan |  7: 0x4ec90e0463d
2|blockMan | 2018-07-26 23:19 +00:00: Database Worker: LMDB Env Initialized.
2|blockMan | 2018-07-26 23:19 +00:00: Performing boot-sync

**Comment by Weiss1985** [comment]
┌───────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬────────┬───────────┬───────┬──────────┐
│ App name          │ id │ mode │ pid   │ status │ restart │ uptime │ cpu    │ mem       │ user  │ watching │
├───────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼────────┼───────────┼───────┼──────────┤
│ api               │ 1  │ fork │ 12416 │ online │ 4       │ 101m   │ 0.2%   │ 64.4 MB   │ weiss │ disabled │
│ blockManager      │ 2  │ fork │ 13690 │ online │ 146     │ 37s    │ 147.8% │ 1.4 GB    │ weiss │ disabled │
│ longRunner        │ 6  │ fork │ 12470 │ online │ 3       │ 101m   │ 0.1%   │ 52.6 MB   │ weiss │ disabled │
│ monero-wallet-rpc │ 9  │ fork │ 12511 │ online │ 1485    │ 101m   │ 0.2%   │ 17.9 MB   │ weiss │ disabled │
│ payments          │ 4  │ fork │ 12439 │ online │ 3       │ 101m   │ 0.1%   │ 45.2 MB   │ weiss │ disabled │
│ pool              │ 7  │ fork │ 12498 │ online │ 3       │ 101m   │ 1.6%   │ 70.1 MB   │ weiss │ disabled │
│ remoteShare       │ 5  │ fork │ 12476 │ online │ 3       │ 101m   │ 0.2%   │ 68.5 MB   │ weiss │ disabled │
│ worker            │ 3  │ fork │ 12434 │ online │ 193     │ 101m   │ 1%     │ 69.2 MB   │ weiss │ disabled │
└───────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴────────┴───────────┴───────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬──────┬─────────────┬───────┐
│ Module        │ version │ target PID │ status │ restart │ cpu  │ memory      │ user  │
├───────────────┼─────────┼────────────┼────────┼─────────┼──────┼─────────────┼───────┤
│ pm2-logrotate │ 2.6.0   │ N/A        │ online │ 0       │ 0.1% │ 21.906 MB   │ weiss │

**Comment by bobbieltd** [comment]
Don’t run monero wallet rpc with pm2 , 12511 restarts, what is error ?
Worker 193 restarts what is error ?

**Comment by Weiss1985** [comment]
logs worker error
`2018-07-27 00:13 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
2018-07-27 01:06 +00:00: Unable to get wallet stats: Unable to process balance
2018-07-27 01:08 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18$
2018-07-27 01:08 +00:00: TypeError: Cannot read property 'block_header' of undefined
    at /home/weiss/nodejs-pool/lib/worker.js:448:32
    at /home/weiss/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/weiss/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/weiss/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/weiss/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/weiss/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at args.(anonymous function) (/home/weiss/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/node_modules/event-loop-inspe$
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-07-27 01:08 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18$
2
2018-07-27 05:06 +00:00: TypeError: Cannot read property 'block_header' of undefined
    at /home/weiss/nodejs-pool/lib/worker.js:448:32
    at /home/weiss/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/weiss/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/weiss/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/weiss/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/weiss/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at args.(anonymous function) (/home/weiss/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/node_modules/event-loop-inspe$
    at _combinedTickCallback (internal/process/next_tick.js:138:11)`

After restart pm2 not start.
Error rpc  mising.

**Comment by bobbieltd** [comment]
What is value of pool.config.daemon.port (check with mysql) ?

**Comment by bobbieltd** [comment]
Is it 18081 ?

**Comment by Weiss1985** [comment]
yes in data base 18081

**Comment by bobbieltd** [comment]
So the issue here is not just blockManager. Your issue is that the modules can not connect to daemon at port 18081.
By the way, if what you are running is graft, port 18981 for daemon. Why graft ? I saw you bind wallet rpc at port 18982 which is normal port for graft wallet rpc.
You should check your coin daemon (monerod or your coin) running at which port and put correct port in config mysql.

**Comment by Weiss1985** [comment]
port 18981 - since daemon took 18081 and 18082.
Coin Monero.
in mysql DB port daemon 18081 rpc 18982

**Comment by bobbieltd** [comment]
Run 
“sudo netstat -nlpt”
Paste output here

**Comment by Weiss1985** [comment]
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1279/redis-server 1
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      2322/init.js
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1138/sshd
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      4046/0
tcp        0      0 0.0.0.0:18080           0.0.0.0:*               LISTEN      1324/monerod
tcp        0      0 0.0.0.0:7777            0.0.0.0:*               LISTEN      2322/init.js
tcp        0      0 127.0.0.1:18081         0.0.0.0:*               LISTEN      1324/monerod
tcp        0      0 127.0.0.1:18082         0.0.0.0:*               LISTEN      1324/monerod
tcp        0      0 0.0.0.0:3333            0.0.0.0:*               LISTEN      2322/init.js
tcp        0      0 127.0.0.1:18982         0.0.0.0:*               LISTEN      2833/monero-wallet-
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      2322/init.js
tcp6       0      0 :::3306                 :::*                    LISTEN      1237/mysqld
tcp6       0      0 :::80                   :::*                    LISTEN      1155/caddy
tcp6       0      0 :::22                   :::*                    LISTEN      1138/sshd
tcp6       0      0 ::1:6010                :::*                    LISTEN      4046/0
tcp6       0      0 :::8000                 :::*                    LISTEN      2213/init.js
tcp6       0      0 :::8001                 :::*                    LISTEN      3354/init.js

**Comment by Weiss1985** [comment]
monerod run -
ExecStart=/usr/local/src/monero/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc

**Comment by bobbieltd** [comment]
I guess “Error: Problem fetching info-- rpc_request:”
/usr/local/src/monero/monerod stop
Try not to put —restricted-rpc
/usr/local/src/monero/monerod --rpc-bind-ip 127.0.0.1 --detach
After some minutes
/usr/local/src/monero/monerod status

**Comment by Weiss1985** [comment]
Daemon - ok
pm2 status
┌───────────────────┬────┬──────┬──────┬─────────┬─────────┬────────┬────────┬───────────┬───────┬──────────┐
│ App name          │ id │ mode │ pid  │ status  │ restart │ uptime │ cpu    │ mem       │ user  │ watching │
├───────────────────┼────┼──────┼──────┼─────────┼─────────┼────────┼────────┼───────────┼───────┼──────────┤
│ api               │ 1  │ fork │ 3354 │ online  │ 1       │ 13h    │ 0.1%   │ 66.1 MB   │ weiss │ disabled │
│ blockManager      │ 2  │ fork │ 7510 │ online  │ 523     │ 25s    │ 130.6% │ 1.4 GB    │ weiss │ disabled │
│ longRunner        │ 6  │ fork │ 2247 │ online  │ 0       │ 13h    │ 0%     │ 54.0 MB   │ weiss │ disabled │
│ monero-wallet-rpc │ 8  │ fork │ 0    │ stopped │ 0       │ 0      │ 0%     │ 0 B       │ weiss │ disabled │
│ payments          │ 4  │ fork │ 2178 │ online  │ 0       │ 13h    │ 0.1%   │ 63.8 MB   │ weiss │ disabled │
│ pool              │ 7  │ fork │ 2322 │ online  │ 0       │ 13h    │ 1.1%   │ 64.5 MB   │ weiss │ disabled │
│ remoteShare       │ 5  │ fork │ 2213 │ online  │ 0       │ 13h    │ 0.2%   │ 71.6 MB   │ weiss │ disabled │
│ worker            │ 3  │ fork │ 6657 │ online  │ 59      │ 2h     │ 0.4%   │ 78.1 MB   │ weiss │ disabled │
└───────────────────┴────┴──────┴──────┴─────────┴─────────┴────────┴────────┴───────────┴───────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬──────┬─────────────┬───────┐
│ Module        │ version │ target PID │ status │ restart │ cpu  │ memory      │ user  │
├───────────────┼─────────┼────────────┼────────┼─────────┼──────┼─────────────┼───────┤
│ pm2-logrotate │ 2.6.0   │ N/A        │ online │ 0       │ 0.1% │ 39.230 MB   │ weiss │
└───────────────┴─────────┴────────────┴────────┴─────────┴──────┴─────────────┴───────┘
 Use `pm2 show <id|name>` to get more details about an app
Blackmanager restart and restart.
And before the reboot, the processor is loaded in 120% and the memory starts to use up to 2GB and after that ALL in reboot ...

**Comment by Weiss1985** [comment]
tried to reinstall on another PC during the installation of not one error.
I started all the same ...

**Comment by Weiss1985** [comment]
Previously, the problem was solved in the following way.
1) cd ~ / nodejs-pool /
node init.js --module = blockManager
2) wait until the base of the blocks is synchronized
3) run cd ~ / nodejs-pool /
pm2 start init.js --name = blockManager --log-date-format = "YYYY-MM-DD HH: mm Z" - -module = blockManager

At the moment it has been working for 15 minutes and so far there is no problem.

The question has not yet arisen.
Perodicheski skips the error -
worker | 2018-07-29 18:29 +00: 00: GetLastBlockHeader Error during block header update

**Comment by Weiss1985** [comment]
[ 0] api     Mem:  70 MB    CPU:  ││ pool > 2018-07-29 19:01 +00:00: (Master) Queue debug state: 0 items in the queue   │
│[ 7] blockManager       Mem: 366  ││ 0 items being processed                                                            │
│[ 5] longRunner     Mem:  56 MB   ││ pool > 2018-07-29 19:01 +00:00: (Master) Queue debug state: 0 items in the queue   │
│[ 1] monero-wallet-rpc     Mem:   ││ 0 items being processed                                                            │
│[ 3] payments     Mem:  50 MB     ││ pool > 2018-07-29 19:01 +00:00: Processed 0/1/0/1 Trusted/Validated/Invalid/Total  │
│[ 8] pm2-logrotate      Mem:  52  ││  shares in the last 30 seconds                                                     │
│[ 6] pool         Mem:  69 MB     ││ worker > 2018-07-29 19:01 +00:00: Block headers identical to historical header.    │
│[ 4] remoteShare     Mem:  67 MB  ││ Ignoring                                                                           │
│[ 2] worker       Mem:  75 MB     ││ pool > 2018-07-29 19:01 +00:00: Performing difficulty update on miners             │
│                                  ││ pool > 2018-07-29 19:01 +00:00: Performing difficulty update on miners             │
│                                  ││ pool > Performing difficulty update on miners                                      │
│                                  ││ pool > 2018-07-29 19:01 +00:00: (Master) Queue debug state: 0 items in the queue   │
│                                  ││ 0 items being processed                                                            │
│                                  ││ pool > 2018-07-29 19:01 +00:00: Performing difficulty update on miners             │
│                                  ││ pool > 2018-07-29 19:01 +00:00: (Master) Queue debug state: 0 items in the queue   │
│                                  ││ 0 items being processed                                                            │
│                                  ││ worker > 2018-07-29 19:01 +00:00: Block headers identical to historical header.    │
│                                  ││ Ignoring                                                                           │
│                                  ││ pool > 2018-07-29 19:01 +00:00: (Master) Queue debug state: 0 items in the queue   │
│                                  ││ 0 items being processed                                                            │
│                                  ││ pool > 2018-07-29 19:01 +00:00: (Master) Queue debug state: 0 items in the queue   │
│                                  ││ 0 items being processed                                                            │
│                                  ││ worker > 2018-07-29 19:01 +00:00: Block headers identical to historical header.    │
│                                  ││ Ignoring                                                                           │
│                                  ││ pool > 2018-07-29 19:02 +00:00: (Master) Queue debug state: 0 items in the queue   │
│                                  ││ 0 items being processed

**Comment by bobbieltd** [comment]
Cannot read property 'block_header' = can not connect to monerod
I don’t understand why your modules could not connect to coin daemon.

**Comment by Weiss1985** [comment]
https://github.com/mesh0000/poolui/issues/29
maybe you know the problem.
