### ISSUE TITLE
v0.13.0.2 support?

### ISSUE THREAD

**Issue by bmnc-team** [Snipa22/nodejs-pool#457]
pool-error.log

2018-10-18 23:12 +08:00: Error: Unknown PoW variant
    at Coin.cryptoNight (/home/pooldaemon/nodejs-pool/lib/coins/xmr.js:166:29)
    at processShare (/home/pooldaemon/nodejs-pool/lib/pool.js:617:33)
    at handleMinerData (/home/pooldaemon/nodejs-pool/lib/pool.js:783:33)
    at handleMessage (/home/pooldaemon/nodejs-pool/lib/pool.js:902:13)
    at Socket.<anonymous> (/home/pooldaemon/nodejs-pool/lib/pool.js:960:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by bobbieltd** [comment]
cd ~/nodejs-pool && npm install
pm2 restart all

**Comment by bmnc-team** [comment]
> cd ~/nodejs-pool && git pull && npm install
> pm2 restart all

Thanks!
